### ISSUE TITLE
Typo in SampSharp.GameMode.SAMP.Commands.CommandAttribute

### ISSUE THREAD

**Issue by fvandillen** [ikkentim/SampSharp#100]
Line 10 has a typo in the word "command".

```Indicates that a method is a player-comammand and specifies information about```

**Comment by rrev** [comment]
Done! (you can change it too and propose a PR!)

**Comment by fvandillen** [comment]
@rrev Yes, I realized it just a little late. My bad, thanks for the fix.

**Comment by rrev** [comment]
No problem :)
