### ISSUE TITLE
Update plugin for 0.3.7

### ISSUE THREAD

**Issue by fvandillen** [ikkentim/SampSharp#107]
As per today, 0.3.7 has been released. We should update SampSharp to reflect changes made by the SAMP devs.

Changes to be made
================

Natives to add
------------------
* [x]  GetPlayerCameraTargetObject(playerid)
* [x]  GetPlayerCameraTargetVehicle(playerid)
* [x]  GetPlayerCameraTargetPlayer(playerid)
* [x]  GetPlayerCameraTargetActor(playerid)
* [x] GetPlayerTargetActor(playerid)
* [x]  GetObjectModel()
* [x]  GetPlayerObjectModel()
* [x] DisableRemoteVehicleCollisions()
* [x] GetPlayerPoolSize()
* [x] GetVehiclePoolSize()
* [x] EnablePlayerCameraTarget()
* [x] SetObjectNoCameraCol()
* [x] SetPlayerObjectNoCameraCol()
* [x] SetVehicleParamsCarDoors(vehicleid, driver, passenger, backleft, backright)
* [x] GetVehicleParamsCarDoors(vehicleid, &driver, &passenger, &backleft, &backright)
* [x] SetVehicleParamsCarWindows(vehicleid, driver, passenger, backleft, backright)
* [x] GetVehicleParamsCarWindows(vehicleid, &driver, &passenger, &backleft, &backright)
* [x] GetVehicleParamsSirenState(vehicleid)
* [x] SetObjectsDefaultCameraCol(disable)
* [x] CreateActor(modelid, Float:X, Float:Y, Float:Z, Float:Rotation)
* [x] DestroyActor(actorid)
* [x] IsActorStreamedIn(actorid, forplayerid)
* [x] SetActorVirtualWorld(actorid, vworld)
* [x] GetActorVirtualWorld(actorid)
* [x] ApplyActorAnimation(actorid, animlib[], animname[], Float:fDelta, loop, lockx, locky, freeze, time)
* [x] ClearActorAnimations(actorid)
* [x] SetActorPos(actorid, Float:X, Float:Y, Float:Z)
* [x] GetActorPos(actorid, &Float:X, &Float:Y, &Float:Z)
* [x] SetActorFacingAngle(actorid, Float:ang)
* [x] GetActorFacingAngle(actorid, &Float:ang)
* [x] SetActorHealth(actorid, Float:health)
* [x] GetActorHealth(actorid, &Float:health)
* [x] SetActorInvulnerable(actorid, invulnerable = true)
* [x] IsActorInvulnerable(actorid)
* [x] IsValidActor(actorid)
* [x] GetActorPoolSize()

Methods to add related to these new natives
--------------------------------------------------------
* [x]  GetPlayerCameraTargetObject(playerid)
* [x]  GetPlayerCameraTargetVehicle(playerid)
* [x]  GetPlayerCameraTargetPlayer(playerid)
* [x]  GetPlayerCameraTargetActor(playerid)
* [x] GetPlayerTargetActor(playerid)
* [x]  GetObjectModel()
* [x]  GetPlayerObjectModel()
* [x] DisableRemoteVehicleCollisions()
* [x] GetPlayerPoolSize()
* [x] GetVehiclePoolSize()
* [x] EnablePlayerCameraTarget()
* [x] SetObjectNoCameraCol()
* [x] SetPlayerObjectNoCameraCol()
* [x] SetVehicleParamsCarDoors(vehicleid, driver, passenger, backleft, backright)
* [x] GetVehicleParamsCarDoors(vehicleid, &driver, &passenger, &backleft, &backright)
* [x] SetVehicleParamsCarWindows(vehicleid, driver, passenger, backleft, backright)
* [x] GetVehicleParamsCarWindows(vehicleid, &driver, &passenger, &backleft, &backright)
* [x] GetVehicleParamsSirenState(vehicleid)
* [x] SetObjectsDefaultCameraCol(disable)
* [x] CreateActor(modelid, Float:X, Float:Y, Float:Z, Float:Rotation)
* [x] DestroyActor(actorid)
* [x] IsActorStreamedIn(actorid, forplayerid)
* [x] SetActorVirtualWorld(actorid, vworld)
* [x] GetActorVirtualWorld(actorid)
* [x] ApplyActorAnimation(actorid, animlib[], animname[], Float:fDelta, loop, lockx, locky, freeze, time)
* [x] ClearActorAnimations(actorid)
* [x] SetActorPos(actorid, Float:X, Float:Y, Float:Z)
* [x] GetActorPos(actorid, &Float:X, &Float:Y, &Float:Z)
* [x] SetActorFacingAngle(actorid, Float:ang)
* [x] GetActorFacingAngle(actorid, &Float:ang)
* [x] SetActorHealth(actorid, Float:health)
* [x] GetActorHealth(actorid, &Float:health)
* [x] SetActorInvulnerable(actorid, invulnerable = true)
* [x] IsActorInvulnerable(actorid)
* [x] IsValidActor(actorid)
* [x] GetActorPoolSize()

Natives to update
----------------------
* [x] CreateVehicle(vehicletype, Float:x, Float:y, Float:z, Float:rotation, color1, color2, respawndelay, addsiren=0)
* [x] AddStaticVehicleEx(modelid, Float:spawn_x, Float:spawn_y, Float:spawn_z, Float:z_angle, color1, color2, respawn_delay, addsiren=0)

Callbacks to add
---------------------
* [x] forward OnVehicleSirenStateChange(playerid, vehicleid, newstate)
* [x] forward OnActorStreamIn(actorid, forplayerid)
* [x] forward OnActorStreamOut(actorid, forplayerid)
* [x] forward OnPlayerGiveDamageActor(playerid, damaged_actorid, Float: amount, weaponid, bodypart);

Callbacks to add to classes/controllers
---------------------
* [x] forward OnVehicleSirenStateChange(playerid, vehicleid, newstate)
* [x] forward OnActorStreamIn(actorid, forplayerid)
* [x] forward OnActorStreamOut(actorid, forplayerid)
* [x] forward OnPlayerGiveDamageActor(playerid, damaged_actorid, Float: amount, weaponid, bodypart);

Constants/enums/enum values to add
------------------------------------------------
* [x] DIALOG_STYLE_TABLIST
* [x] DIALOG_STYLE_TABLIST_HEADERS

Classes to add
-------------------
* [x] Actor

Methods to add / modify
------------------------------
* [x] Dialog.X => anything related to tablists
* [x] GtaVehicle.Create/X => anything spawning related

**Comment by ikkentim** [comment]
I'm on it.

**Comment by ikkentim** [comment]
Natives to add:
* [ ]  GetPlayerCameraTargetObject(playerid)
* [ ]  GetPlayerCameraTargetVehicle(playerid)
* [ ]  GetPlayerCameraTargetPlayer(playerid)
* [ ]  GetObjectModel()
* [ ]  GetPlayerObjectModel()

Classes to add:
* [ ] Actor

Methods to modify / add
* [ ] Dialog.X => anything related to tablists

**Comment by ikkentim** [comment]
Added to do list to the issue. Please tell me if I missed something.

**Comment by fvandillen** [comment]
Seems good so far, i'll review the list tonight and comment if you missed anything.
