### ISSUE TITLE
Need clarification

### ISSUE THREAD

**Issue by zameeramir** [ikkentim/SampSharp#117]
I did not understood this point on https://github.com/ikkentim/SampSharp/wiki/Installing-MySql.Data.dll-on-linux
Locate MySql.Data.dll for .NET 4.5 and change to it's directory. (usually in /v4.5/)

Does it mean I shall move these dlls to some folder? Can you guide me to /v4.5/

**Comment by ikkentim** [comment]
Did you know the _cd_ command stands for _change directory_?

'cd (directory of MySql.Data.dll)  ' and continue with the instructions.

**Comment by ikkentim** [comment]
@zameeramir Did this solve your problem?

**Comment by ikkentim** [comment]
I'm assuming you solved it. If not, please leave a reply.
