### ISSUE TITLE
Revamp/rewrite command system

### ISSUE THREAD

**Issue by ikkentim** [ikkentim/SampSharp#129]
The current "detectable command" system is very messy and lacks some features. I think it would be best to rewrite it.

Requirements of command system:

- [x] There should be a general interface for commands.
- [x] You should be able to create commands using classes.
- [x] A command can have multiple names (/w /whisper /wh ,... decided by the user)
- [x] **The system should be clean and easily extendable**.

``` c#
interface ICommand
{
    CommandCallableResponse CanCall(BasePlayer player, string commandText);
    bool Call(BasePlayer player, string commandText);
}

enum CommandCallableResponse
{
    False, // The specified parameters don't allow this command to be called
    True, // The specified parameters require this command to be called
    Optional // The specified parameters allow this command to be called unless a different command accepts the parameters
}
```

Requirements of the detected command system:
- [x] You should be able to create commands using attributes.
- [x] Arguments can be optional.
- [x] Text case can be ignored.
- [x] Commands can easily be grouped `/admin vehicle spawn`.
- [x] Available commands should be listable.
- [x] You should be able to provide a "primary name" of a command (Can be used in help lists).
- [x] Intended argument types should be cleverly detected, e.g. if the last arugment is a string, it can be assumed it is a string of words (not a single word). This behavior should be override-able using attributes.
- [x] **The system should be clean and easily extendable**.

(Still some to be added, suggestions welcome).

**Comment by rrev** [comment]
"create commands using classes"

?? 

A command is a list of actions after all, a class per command doesn't fit at all. And what is     CommandCallableResponse CanCall(BasePlayer player, string commandText);?

**Comment by ikkentim** [comment]
*"A command is a list of actions after all, a class per command doesn't fit at all"*

Currently this is already the case, this is the current structure of how commands are loaded and run:
![](http://www.quick-screen.co.uk/1z8l80)

I sort of want to do the same thing again, but instead of a command base class have an interface and a totally free implementation. Commands are stored in a list of instances, which is checked against every time a command is run.

*"And what is CommandCallableResponse CanCall(BasePlayer player, string commandText);?"*

Basically, the new `CommandCallableResponse CanCall(...)` replaces all `HasPlayerPermissionForCommand`, `CommandTextMatchesCommand` and `AreArgumentsValid` methods.

Determined by the command name (`/name arg1 arg2`) and other factors (such as argument types, permissions, etc) the command can decide whether the command can be called: `False`, `True` or `Optional`. 

Example:
There are 3 instances of command, each represent one of the following:
- `/saynumber [integer]`
- `/saynumber [float]`
- `/say [text]`

If the entered command is `/say hello` `CanCall` for both `/saynumber` will return `False` and `/say` will return `True`, because it matches the command name and the arguments.

If the entered command is `/say 3.14` `CanCall` for `/saynumber [integer]` will(or can) return `Optional` which means that this command will be called if no other command returns True, however `/saynumber [float]` does return `True` meaning that this command will be called.

The reason `/saynumber [integer]` returns `Optional` is because the call to this command can handle the "invalid arguments" message, but only if there is no overload which accepts the given arguments(`3.14`). As you can see this new system can accept overloads properly, the current system can't, because it only checks the name.

The reason I don't want to restrict people to the `DetectedCommand` system and allow custom command implementations is so users can created other advanced command systems which may not be possible with the limitations of the build in framework version. By creating this interface all command systems can work together just fine.

**Comment by ikkentim** [comment]
Completed, but documentation is still needed.

**Comment by ikkentim** [comment]
Documentation partially completed
http://sampsharp.timpotze.nl/player-commands-vnext

**Comment by ikkentim** [comment]
Docs completed.
