### ISSUE TITLE
Pickups and Textlabels Dont Appear

### ISSUE THREAD

**Issue by arcnat** [ikkentim/SampSharp#132]
Hi,

I'm developing a gamemode with SampSharp library. I have to thank you Tim, it's a really great job. 

But whenever I try to create a new pickup or create a new textlabel, it seems it was created but it doesnt appear in the game. 

Here is my code sample:
Pickup.Create(1272, 1, new Vector3() { X = 1831.736F, Y = -1842.36F, Z = 13.57812F }, -1);

There should be a blue house pickup into the 24/7 market nearby train station in los santos.

**Comment by rrev** [comment]
If you try the same pickup id/type and location with PAWN the pickups gets created?

**Comment by ikkentim** [comment]
I tried your exact code
![](http://puu.sh/lY8qk/6c4eead436.jpg), works just fine for me.

**Comment by arcnat** [comment]
I removed NuGet package, downloaded binary file and called local dll than it worked fine.
