### ISSUE TITLE
"native not found" Error (CreateDynamicObjectEx)

### ISSUE THREAD

**Issue by arcnat** [ikkentim/SampSharp#136]
When I create new DynamicObject instance I get "native not found" error message on server: 
![notfound](https://cloud.githubusercontent.com/assets/15607441/11983558/ea93c1ea-a9bc-11e5-8c51-c1eae66f0962.PNG)

It seems streamer cant find CreateDynamicObjectEx function. Can you try it?

Here is my code:
![ek](https://cloud.githubusercontent.com/assets/15607441/11983592/30934c92-a9bd-11e5-9646-0b4d7c326154.png)

**Comment by ikkentim** [comment]
Did the streamer load successfully?

**Comment by arcnat** [comment]
I think yes. Should I do anything more than call streamer referance?

**Comment by arcnat** [comment]
I add SampSharp.Streamer.dll into plugins but it doesnt loading correctly. 

![st2](https://cloud.githubusercontent.com/assets/15607441/11993559/116c8062-aa3b-11e5-88d1-0c145a11834a.PNG)
![st3](https://cloud.githubusercontent.com/assets/15607441/11993560/118af9c0-aa3b-11e5-831f-5dea70f88060.PNG)
![st1](https://cloud.githubusercontent.com/assets/15607441/11993561/119dd8ec-aa3b-11e5-89f4-521075c8fd05.PNG)

**Comment by WopsS** [comment]
Hello, 

Sorry if my answer is not as excepted, but from what I understand your gamemode doesn't find a function from streamer, right? 

I think you need to load streamer before your gamemode. By the way check why steamer isn't loading.

**Comment by WopsS** [comment]
I can't edit my reply, add streamer.dll to your plugins folder.

**Comment by arcnat** [comment]
Hi WopsS
Thanks for your reply but I tried many variations before. 

Like
plugins SampSharp SampSharp.Streamer
plugins SampSharp streamer
plugins streamer SampSharp
plugins SampSharp.Streamer SampSharp etc.

In an example project @ikkentim used this line: "plugins SampSharp streamer" and I did it too. But server cant load it.

**Comment by ikkentim** [comment]
I see your error but im not home, Will respond asap

Groeten,
Tim Potze.

**Comment by ikkentim** [comment]
SampSharp.Streamer is an **wrapper** for the streamer plugin. You need to download and install the [streamer plugin](http://forum.sa-mp.com/showthread.php?t=102865), and add it to your `plugins` line in your server.cfg.

Next, you can add SampSharp.Streamer.dll to your references of your game mode project -OR- add the SampSharp.Streamer NuGet package to your game mode references.

**Comment by arcnat** [comment]
Thank you so much Tim, problem solved. I think you should note this on your documentation.
