### ISSUE TITLE
[Q] Running on normal .NET in windows server.

### ISSUE THREAD

**Issue by JohnyMac** [ikkentim/SampSharp#138]
Hello, 
I never worked with mono so I don't know whats the difference and how to move from .NET to mono or vice versa so I just wanted to ask if its possible to run this plugin on normal .NET in a windows server ?

**Comment by ikkentim** [comment]
You cant run it on .net. The plug-in relies on the mono vm it is running. You simply have to download it and store it in the server directory. http://sampsharp.timpotze.nl/installation#install-mono

**Comment by JohnyMac** [comment]
Yeah I see but AFAK, Mono is just a replica of .NET but with the fact that its cross platform, right ?
So it would be useful if ran on Linux or something, But in windows.. Is it possible to just use .NET itself ?

If not, You may just close the issue then.. I got what i want.

**Comment by ikkentim** [comment]
Aside from the fact that I did not find an easy way to create a .NET VM, I didn't feel like writing the plugin twice(Win/Lin).

Anyhow, thanks for your interest in this project! Expect more documentation and stability in the future!

**Comment by JohnyMac** [comment]
Thanks a lot for the project mate :)
I am looking forward to create a RP gamemode and release it and also to contribute for sure.

I am just liking it very much, again, thanks for your efforts.
