### ISSUE TITLE
Add the ability to define new natives, accessible from Pawn filterscripts and etc?

### ISSUE THREAD

**Issue by Xalphox** [ikkentim/SampSharp#139]
Useful if you want to give third party developers (most of which might not know C#) the ability to interface with the core gamemode

**Comment by ikkentim** [comment]
I don't think I'll be implementing this. The focus of this project is to allow users to create gamemodes in c#. If you're dying for some way to communicate with filter scripts, use callbacks. Use CallRemoteFunction in your fs, implement the callback in your gamemode class.
