### ISSUE TITLE
Tools.Disposable is not thread safe

### ISSUE THREAD

**Issue by Xalphox** [ikkentim/SampSharp#140]
Just had an issue with IsDisposed where despite being set in thread A, I got "object is disposed" exception in thread B (probably due to caching).

I think this would be fixed by making IsDisposed volatile @ikkentim :)

**Comment by ikkentim** [comment]
Sorry for the late response! 

I'll fix this in the next version. I'm guessing there are more non-threadsafe parts and I'm still not sure if the natives system is 100% threadsafe.(though I've done my best to make it so)

**Comment by Xalphox** [comment]
No problem! Thanks for all your hard work on this!
