### ISSUE TITLE
Debug in Visual Studio 2015

### ISSUE THREAD

**Issue by digovc** [ikkentim/SampSharp#141]
Hi ikkentim,

First of all, thanks for great job! Really amazing!
I know this is not best location to make this question, but go ahead:

It's possible use debug tools of Visual Studio 2015 with the server runing, like a normal program in c#?

**Comment by ikkentim** [comment]
I tried, but sadly it isn't possible.

**Comment by digovc** [comment]
Tks.

**Comment by digovc** [comment]
I think this happened because you use mono in place of .net.
Do you agree?

**Comment by ikkentim** [comment]
Yes

**Comment by digovc** [comment]
Ok.

Can I change this to use .net? I hope use a windows server with my mod.
Just build again using .net it's will works?

Em seg, 15 de fev de 2016 às 04:16, Tim Potze <notifications@github.com>
escreveu:

**Comment by ikkentim** [comment]
No. The plugin runs a mono VM. There’s no way of doing this in .NET and the plugin wouldn’t support it.

**Comment by digovc** [comment]
I understand.
And thanks again. If you need help, call me!

Em seg, 15 de fev de 2016 às 08:43, Tim Potze <notifications@github.com>
escreveu:
