### ISSUE TITLE
Questions about sampSharp

### ISSUE THREAD

**Issue by vsLightningStormGit** [ikkentim/SampSharp#142]
I am a CSharp engineer, I don't understand c + + language, your program to help me a lot.I hope you can help me a little busy.In c + + language is adding a can output to the console in both English and Chinese.Brother, I will thank you very much.

**Comment by ikkentim** [comment]
If you're talking about sampsharp printing chinese, configure the encoding used: http://sampsharp.timpotze.nl/configuration#encoding

If you're talking about doing this in c++ and outputting it into the sa-mp console, I convert my characters here:
https://github.com/ikkentim/SampSharp/blob/master/src/SampSharp/unicode.cpp

If you're talking about c++ in general, check wcout:
http://www.cplusplus.com/reference/iostream/wcout/

**Comment by vsLightningStormGit** [comment]
Thank you !!!
