### ISSUE TITLE
Questions about the console output in both Chinese and English

### ISSUE THREAD

**Issue by vsLightningStormGit** [ikkentim/SampSharp#143]
Hello, sorry to trouble you can tell me about where to modify the code, properly show both English and Chinese characters on the console.I am a rookie, c + + completely don't understand the meaning.Trouble master, do me this favor, thank you, I would be grateful!

**Comment by ikkentim** [comment]
Which console? Do you mean printing Chinese using SampSharp? Do you mean printing Chinese in the SA-MP console?

**Comment by vsLightningStormGit** [comment]
yes

**Comment by ikkentim** [comment]
Yes is the answer to which of the three questions?

**Comment by vsLightningStormGit** [comment]
I don't know, I enter a Chinese, the console output is a question mark，What method can solve the console output not garbled in Chinese? and Input English is normal

**Comment by vsLightningStormGit** [comment]
I don't know, I enter a Chinese, the console output is a question mark，What method can solve the console output is garbled in Chinese? and Input English is normal

**Comment by JohnyMac** [comment]
I THINK he means to output chinese using sampsharp, But he keeps saying c++ by wrong...

> If you're talking about sampsharp printing chinese, configure the encoding used: http://sampsharp.timpotze.nl/configuration#encoding

**Comment by vsLightningStormGit** [comment]
Do you know the code display output of Chinese,JohnyMac

**Comment by JohnyMac** [comment]
I don't really know how to set the codepage, if thats your questions..  @ikkentim ?
Pretty sure it will be code *936* though..

**Comment by ikkentim** [comment]
Just put
```
codepage 936
```

in your server.cfg config file.

**Comment by vsLightningStormGit** [comment]
Yes, but no 963 coding

**Comment by vsLightningStormGit** [comment]
Yes, but no 936 coding

**Comment by vsLightningStormGit** [comment]
I've tried, the same problem, can't show Chinese

**Comment by JohnyMac** [comment]
Try 950..

**Comment by ikkentim** [comment]
Have you set your locale of windows to Chinese?

**Comment by vsLightningStormGit** [comment]
950 no。。

**Comment by vsLightningStormGit** [comment]
My Windows are in Chinese

**Comment by vsLightningStormGit** [comment]
Do you have a way to solve the output Chinese?

**Comment by vsLightningStormGit** [comment]
Your SampSharp does not support Chinese code?

**Comment by ikkentim** [comment]
In addition to settings the codepage in the server.cfg file, you'll also need to configure your Windows machine to use this code page for ansi programs http://knowledgebase.progress.com/articles/Article/4677

**Comment by vsLightningStormGit** [comment]
good.I'll give it a try

**Comment by vsLightningStormGit** [comment]
But, I'm a non-unicode programs of the default language is Chinese simplified

**Comment by ikkentim** [comment]
Turns out code page 963 is not supported by sampsharp. A fix will be released soon.

**Comment by ikkentim** [comment]
This *should* be resolved with b3c1e41. Are you able to test this? @vsLightningStormGit 
You need this folder in your server folder https://github.com/ikkentim/SampSharp/tree/master/env/codepages
and you'll need to compile the plugin.
If you need any help, please ask! :)
