### ISSUE TITLE
Command attribute not picked up in other assemblies

### ISSUE THREAD

**Issue by Xalphox** [ikkentim/SampSharp#144]
Although I imagine this may already have been fixed in 0.7.0 - if you have a multi-project environment, [Command] attributes will only be found in the current assembly.

(I have a setup where I have a framework project which I plan to reuse between gamemodes, and the actual gamemode logic in a separate project).

**Comment by ikkentim** [comment]
This is the default behavior, not wanting to create unnecessary overhead.

In your Initialized method of the game mode:
```
Controllers.OfType<CommandController>().FirstOrDefault().RegisterCommands(GetType());
```

In v0.7.0 (unreleased, and I don't have much time for it in the near future) this code has been rewritten and it has to be registered differently, I'll document it at the time of the release of the new version.

**Comment by Xalphox** [comment]
Thanks!
