### ISSUE TITLE
SampSharp Plugin Fails When Server Up

### ISSUE THREAD

**Issue by tuhaf** [ikkentim/SampSharp#145]
Hey,

I had been developing a gamemode with SampSharp library until two months ago. Last week I changed my computer(Now I'm using Windows 10, before it was Windows 8.1) and today I tried to run samp-server.exe but SampSharp plugin didnt load.

I checked everything(Mono is installed, and mono files are exist in env)  but i couldnt find the problem. Then I download last release files, followed steps which are in the "Starting Development" page and created a new SampSharp project. Same thing happened again, SampSharp plugin didnt load...

Finally i tried to run it on my server (Windows Server 2008) and it failed again.

Do you have any idea for it? Do I forgetting something?

**Comment by fvandillen** [comment]
Do you have a server log available?

**Comment by tuhaf** [comment]
Here it is:

----------
Loaded log file: "server_log.txt".
----------

SA-MP Dedicated Server
----------------------
v0.3.7-R2, (C)2005-2015 SA-MP Team

[23:38:15] 
[23:38:15] Server Plugins
[23:38:15] --------------
[23:38:15]  Loading plugin: SampSharp
[23:38:16]   Failed.
[23:38:16]  Loaded 0 plugins.

[23:38:16] 
[23:38:16] Filterscripts
[23:38:16] ---------------
[23:38:16]   Loaded 0 filterscripts.

[23:38:16]   Filterscript 'empty.amx' loaded.
[23:38:16] Number of vehicle models: 0

And my server.cfg file:
echo Executing Server Config...
lanmode 0
rcon_password sadrew1321s
maxplayers 50
port 7777
hostname SS RPG | SS.com
announce 0
query 1
chatlogging 0
weburl www.SS.com
onfoot_rate 40
incar_rate 40
weapon_rate 40
stream_distance 300.0
stream_rate 1000
maxnpc 0
logtimeformat [%H:%M:%S]

#
# SA-MP#
#
gamemode0 empty 1

# Windows (append other plugins)
plugins SampSharp

# Linux (append other plugins)
# plugins SampSharp.so

# symbols gamemode/SampSharp.GameMode.dll gamemode/SS.RPG.GAME.MODE.dll
gamemode SS.RPG.GAME.MODE:GameMode
codepage 1254

**Comment by ikkentim** [comment]
Could you try using http://www.dependencywalker.com/ ?

**Comment by tuhaf** [comment]
What should i do with it?

**Comment by ikkentim** [comment]
Run it against SampSharp.dll to find missing dependencies

**Comment by tuhaf** [comment]
When I run it against sampsharp.dll, it shows like this:
![Uploading sampsharperror.png…]()

**Comment by Seprum** [comment]
Seems like the mono is not recognized. Are you sure that you have downloaded mono from the [link](http://deploy.timpotze.nl/packages/mono-portable4.zip) posted on wiki Installation page? Check if your server hierarchy has this kind of structure:
```
env/
    plugins/
            SampSharp.dll
            ...
        mono/
            etc/
            lib/
        filterscripts/
            empty.amx
            ...
        gamemodes/
            empty.amx
            ...
        gamemode/
            SampSharp.GameMode.dll
            YourGamemode.dll
        samp-server.exe
        ...
```

**Comment by Seprum** [comment]
I assume you are running x86 version of Windiws 10? Have you built SampSharp plugin by yourself or just downloaded it? From what Dependency Walker says, your plugin is using Windows x64 standart libraries hovewer it is supposed to use x86 ones.

**Comment by tuhaf** [comment]
I'm running x64 version of Windows 10. Before that It was x64 version of Windows 8.1 
I built it myself and referred them to my project.  And my server hierarchy is same as you wrote. But still it doesnt work.

**Comment by ikkentim** [comment]
Have you got mono-2.0.dll in your server folder?

**Comment by ikkentim** [comment]
@tuhaf see previous message

**Comment by tuhaf** [comment]
Oh, you're right Tim. I forgot it. Thank you so much.
