### ISSUE TITLE
SetAttachedObject and Special Actions

### ISSUE THREAD

**Issue by tuhaf** [ikkentim/SampSharp#153]
Hi,

When I use SetAttachedObject, it works fine for first player in the server  but for other players it doesnt work, it sets again to first player. (it is always sets for which player has 0 id)

And second issue is about Special Actions. When I set a speacial action to a player it works. But when i set again different action or None value, it doesnt work, first action doesnt stop.

Can you check these?

**Comment by ikkentim** [comment]
The special actions code looks just fine. I don't have the time in the next few days to test it, I'll test later. Notice some actions can not be set: http://wiki.sa-mp.com/wiki/SpecialActions

SetAttachedObject also seems to be implemented just fine:
https://github.com/ikkentim/SampSharp/blob/fc9106a38a51cab365f5def667c7ce7744d5fbc5/src/SampSharp.GameMode/World/BasePlayer.cs#L1312

Maybe it's an error on your part; can you share a bit of your code where you invoke these methods?

**Comment by tuhaf** [comment]
Under player(generates GtaPlayer) class:

```
  public override void OnSpawned(SampSharp.GameMode.Events.SpawnEventArgs e)
        {
            SetAttachedObject(9, 1210, Bone.LeftHand, new SampSharp.GameMode.Vector3(), new SampSharp.GameMode.Vector3(), new SampSharp.GameMode.Vector3(1, 1, 1), new Color(), new Color());
            
            e.ReturnToClassSelection = false; 
        }
```

It works for first player(id:0) but doesnt work for others. There is no more attached objects.

**Comment by ikkentim** [comment]
I've tried it, and it seems to work just fine for me :/

**Comment by ikkentim** [comment]
Been confirmed it works, at least under 0.7 pre-releases.
