### ISSUE TITLE
Console.Title as Hostname

### ISSUE THREAD

**Issue by eXeGOODER** [ikkentim/SampSharp#155]
Trifle, but it is pleasant

**Comment by ikkentim** [comment]
How do you mean?

**Comment by eXeGOODER** [comment]
You planned to add operation with 'server.cfg'.
Here I also thought to make console title as 'hostname'

**Comment by ikkentim** [comment]
The behavior of Console.Title cannot be overriden and this is also not the purpose of the Console class.

You can access the hostname anyways by using `Server.GetConsoleVariable<string>("hostname")`
For setting, you'll need to use `Server.SendRconCommand("set hostname X")`

I see how a simple property would be nicer, but for now, the framework only wraps around the native functions of SA-MP. Adding functionality is something for https://github.com/ikkentim/SampSharp-utilities , which I will be working on in the future

**Comment by eXeGOODER** [comment]
`server.cfg`:
`title Your Hostname Here`
