### ISSUE TITLE
Integrating 3rd Party Plugin

### ISSUE THREAD

**Issue by arcnat** [ikkentim/SampSharp#157]
Hi,

I saw Mauzen's RNPC plugin in samp forum yesterday. I want to integrate it in my project which has been developing with SampSharp library. 

I add its dll into my plugins directory and cfg, loaded npcmodes. But when I try to control if plugin is loaded with Native.NativeExists("RNPC_StartPlayback") method, it returns false,

Which steps I should follow to integrate this plugin?

**Comment by ikkentim** [comment]
Im currently on vacation. I'll check later

**Comment by ikkentim** [comment]
I've checked it out (sorry! a little late...) and the `Native.NativeExists` function works just fine. Please take a look at the `rnpc.inc` file. you'll find this:
```

/**
 *  Tells the NPC to start playback of any rec file
 *	@since	V0.1.1
 */
stock RNPC_StartPlayback(npcid, rec[])
{
	if (!IsPlayerRNPC(npcid)) return false;
	
	new form[40];
	format(form, 40, "RNPC:109:%s", rec);
	SendClientMessage(npcid, -1, form);
	
	return true;
}
```

so `RNPC_StartPlayback` is not a native, but a stock function. You'll need to check for a native function, such as `RNPC_CreateBuild`.
