### ISSUE TITLE
DynamicObjectController - RegisterTypes not marked as virtual

### ISSUE THREAD

**Issue by Xalphox** [ikkentim/SampSharp#164]
Unless I'm mistook - I figure this needs to be marked as virtual in order to call .Register.

Work around as of present is to use a different controller - whether it's BaseVehicleController or not, the plugin doesn't seem to care what types you register there.

**Comment by ikkentim** [comment]
This is a about the streamer plugin ( https://github.com/ikkentim/SampSharp-streamer ) I created a new issue there. Virtual only means you can override it in a sub type. But yes, it it sensible to mark it virtual so other users can override its functionality.
