### ISSUE TITLE
Request: silently fail instead of throwing NativeNotImplemented when set to "unit test mode"

### ISSUE THREAD

**Issue by Xalphox** [ikkentim/SampSharp#165]
Or alternatively some sort of framework to mock natives - including existing ones under BaseMode - either would work well for me.

**Comment by ikkentim** [comment]
Is coming up here: https://github.com/ikkentim/sampsharp-mockery

Still needs a whole lot of work. Will leave this issue open until the first version of mockery is ready.

**Comment by ikkentim** [comment]
With .Entities this shouldn't be much of a problem anymore. I won't be building unit test support for .GameMode due to the sheer amount of effort it would take
