### ISSUE TITLE
Last alpha version chrash

### ISSUE THREAD

**Issue by MagicIsArt** [ikkentim/SampSharp#170]
Log file:
`
----------
Loaded log file: "server_log.txt".
----------

SA-MP Dedicated Server
----------------------
v0.3.7-R2, (C)2005-2015 SA-MP Team

[23:15:33] 
[23:15:33] Server Plugins
[23:15:33] --------------
[23:15:33]  Loading plugin: SampSharp
[23:15:33] 
[23:15:33] SampSharp Plugin
[23:15:33] ----------------
[23:15:33] v0.7.6133.31753, (C)2014-2016 Tim Potze
[23:15:33] 
`

I update mono and samp server.

**Comment by donshius** [comment]
I am having the same issue.

**Comment by ikkentim** [comment]
Lines 45 and 63 of which file are you talking about @donshius ?

**Comment by donshius** [comment]
Sorry, very stupid of me not to mention the file, it was the Config.h file.

**Comment by ikkentim** [comment]
This issue has been fixed in 601ec252dba1ca1873c9b8931640a03811ba0f59
