### ISSUE TITLE
Extend BasePlayer

### ISSUE THREAD

**Issue by Zierk59** [ikkentim/SampSharp#172]
Hi, is there way to extend BasePlayer class? I want to add new proporties (with permissions etc) and use it in IPermissionChecker. 
I created new class (Player) based on BasePlayer, but I can't use it in IPermissionChecker because interface force to use BasePlayer class as parametr in Check method. I'm not very advanced in C# but I want to learn it with your amazing libary.

For example:

> public class Player : BasePlayer
    {
        #region Types
        public enum PlayerPermissions
        {
            User,
            Moderator,
            Administrator,
            Programmer
        };
        #endregion
        private PlayerPermissions _Permission = PlayerPermissions.User;
        public PlayerPermissions Permission
        {
            get { return _Permission; }
            set { _Permission = value; }
        }
    }

And I want use it here

` class Administrator : IPermissionChecker`
`    {`
`        public string Message`
`        {`
`            get { return Messages.Global.szErrorPermissions; }`
`        }`
`        public bool Check(BasePlayer player)`
`        {`
`            return player.Permission >= Player.PlayerPermissions.Administrator ; // <--------- HERE`
`        }`
`    }`
Sorry for spamming in Issues.

**Comment by WopsS** [comment]
Hello,

You can **cast** it to your player class.
```C#
(Player)Convert.ChangeType(player, Player);
```

**P.S**: Don't forget to make the enum static or use **player**, not **Player**.

https://msdn.microsoft.com/en-us/library/dtb69x08(v=vs.110).aspx

**Comment by ikkentim** [comment]
Hang on

**Comment by Zierk59** [comment]
Thank you
