### ISSUE TITLE
Server not works correctly on Linux

### ISSUE THREAD

**Issue by 5LICK** [ikkentim/SampSharp#174]
After connect to server, i can't spawn correctly and i see `loading...` message on the screen.

I using docker for run server, on the ubuntu 32bit and with installed package `mono-complete` version 4.6
Also, when running server using virtual machine (without docker), i got same problem (but without `loading..` message).

On the Windows, all works fine with identical settings and gamemode.

gdb stacktrace (crash moment): http://pastebin.com/v2ZSmP1Y
gdb values of local variables: http://pastebin.com/54Rsxr4p

**Comment by ikkentim** [comment]
I tried running sampsharp in a ubuntu vm, and it seems to be working fine there. I haven't yet tried to run it in docker, because Docker isn't working right now on my windows machine, will test docker later.

**Comment by 5LICK** [comment]
How? It is good, i will try run Sampsharp on linux soon

**Comment by ikkentim** [comment]
I ran it in virtual box, will try it soon on a vm hosted elsewhere.

**Comment by ikkentim** [comment]
This has been resolved in the 0.8.0 prerelease.
