### ISSUE TITLE
Codepage translation might not be working probably

### ISSUE THREAD

**Issue by ikkentim** [ikkentim/SampSharp#175]
> I have some problems with Russian text, i used codepage cp1251, but it is not works correctly
> i need to make something else?
>
> Tim Potze @ikkentim 16:36
> do you have the folder named codepages in your server directory, at least container cp1251.txt?
>
> Oleg @5LICK 16:36
> yes
>
> Tim Potze @ikkentim 16:36
> 
> Does it show weird characters or something?
> 
> Oleg @5LICK 16:38
> i got string - ⬨⬨⬨⬨⬨⬨
> or something similar
> rhombuses

**Comment by 5LICK** [comment]
⬨⬨⬨⬨⬨⬨ - wrong
ðóññêèé - real output string in the logs

**Comment by 5LICK** [comment]
It is happen only on linux

**Comment by ikkentim** [comment]
Seemed to have been a problem with the linux configuration?

**Comment by 5LICK** [comment]
I changed my locale from `en_US.UTF-8` to `ru_RU.UTF-8` and i reconfigured locales. System has been used Russian text, but when i run my server, in the log file is same result.

**Comment by ikkentim** [comment]
What do you use to view the log files? terminal/cat/more?

**Comment by 5LICK** [comment]
@ikkentim uhh, You right! That's problem in the text editor. Codepage translation works correct!
Because by default server log in the `ISO 8859-1` encoding.

**Comment by ikkentim** [comment]
Good to see it's solved then! :+1:
