### ISSUE TITLE
why i see in my console this error

### ISSUE THREAD

**Issue by tiuman** [ikkentim/SampSharp#176]
ERROR: Couldn't find class YourGameMode:GameMode!
  Failed.

but i create Project with namespace YourGameMode and copy class from this http://sampsharp.timpotze.nl/starting-development. i owerwrited Server config tamplate. 
all step by step my configuration equal with this tutorial? i have VS2015

**Comment by ikkentim** [comment]
Are you sure you have a class named GameMode which inherits from BaseMode on you YourGameMode namespace?

**Comment by tiuman** [comment]
yes

**Comment by tiuman** [comment]
closed! it error has been because i write small char on YourGameMode  YourGamemode
