### ISSUE TITLE
About it BaseVehicle class to FindOrCreate method questions.

### ISSUE THREAD

**Issue by vsLightningStormGit** [ikkentim/SampSharp#177]
Have a bug,Need handle it.The BaseVehicle class to FindOrCreate method. When input property for vehicle ID. it can't build vehicle for on the game. I trying to this respawn method,too.  can't. So, if haven't bug. I hope you can tell me,How do the use it. Thank you.

**Comment by ikkentim** [comment]
I'm sorry, but I don't quite understand your question? What are you trying to achieve? Are you trying to spawn a vehicle perhaps?

**Comment by vsLightningStormGit** [comment]
Yes. Sorry about 'build',I write wrong. How using vehicle id spawn a vehicle?

**Comment by ikkentim** [comment]
FindOrCreate is not the method you need. You're looking for the Create method: 
http://api.sampsharp.timpotze.nl/html/83b6163c-6b28-7b85-bb3a-fbc7b362615e.htm

http://api.sampsharp.timpotze.nl/html/2d1426e2-8597-7b2f-6689-ea7e842e4c76.htm

http://api.sampsharp.timpotze.nl/html/30ada40d-5913-3915-8fe2-c4d8574d3ced.htm

**Comment by vsLightningStormGit** [comment]
Thank you very much.
