### ISSUE TITLE
Where tutorial for native callback and how natives callbacks use? forexample OnPlayerSpawn etc

### ISSUE THREAD

**Issue by tiuman** [ikkentim/SampSharp#178]
Notice! Callbacks provided by SA-MP are all handled by the framework by default. This documentation can be used for handling custom callbacks and callbacks provided by various plugins.

**Comment by ikkentim** [comment]
Do you mean, how to use callbacks?

To take your example, OnPlayerSpawn, either:

- hook onto the [PlayerSpawned](http://api.sampsharp.timpotze.nl/html/3bb7eaa8-1ac1-c035-f922-d456fbd8e5e0.htm) event in your gamemode
- override [OnPlayerSpawned](http://api.sampsharp.timpotze.nl/html/937e60e5-7867-d46e-f5c8-ef39bba69031.htm) in your gamemode
- hook onto the [Spawned](http://api.sampsharp.timpotze.nl/html/5e94839f-be1d-f23c-1127-3e7e4dc7dae6.htm) event of the player you're interested in
- override [OnSpawned](http://api.sampsharp.timpotze.nl/html/7ec15aee-b211-6774-5cb3-591339bbdea8.htm) in your own Player implementation

Like the documentation says (the part you copied into this issue), all default SA-MP callbacks are handled by SampSharp and propagated to events and their respective objects. Simply hook onto their events or override the event raising method (e.g. OnSpawned(...) and OnPlayerSpawned(...) in the example above).

**Comment by tiuman** [comment]
i am sorry but your may see me example implemented evets?

**Comment by ikkentim** [comment]
>hook onto the PlayerSpawned event in your gamemode
``` c#
public class GameMode : BaseMode
{
    protected override void OnInitialized(EventArgs e)
    {
        base.OnInitialized(e);
        // ...
       
        // this can also be done from anywhere else in your library
        this.PlayerSpawned += (sender, args) => {
              // do something
        };

    }
}
```

>override OnPlayerSpawned in your gamemode
``` c#
public class GameMode : BaseMode
{
    protected override void OnPlayerSpawned(BasePlayer player, SpawnEventArgs e)
    {
        base.OnPlayerSpawned(player, e);

        // do something
    }
}
```


>hook onto the Spawned event of the player you're interested in
``` c#
[PooledType] // indicate this class overrides the default player class
public class Player : BasePlayer
{
    protected override void OnConnected(EventArgs e)
    {
        base.OnConnected(e);
        // ...
       
        // this can also be done from anywhere else in your library
        this.Spawned += (sender, args) => {
              // do something
        };

    }
}
```

>override OnSpawned in your player
``` c#
public class GameMode : BaseMode
{
    protected override void OnSpawned(SpawnEventArgs e)
    {
        base.OnSpawned(e);

        // do something
    }
}
```

But in all honesty, these are C# basics, maybe you should search for some C# tutorials.

**Comment by tiuman** [comment]
thenks
