### ISSUE TITLE
what  have the method fast and simple creating and save user data?

### ISSUE THREAD

**Issue by tiuman** [ikkentim/SampSharp#180]
for example SetPVar or other...
i am implementing this so:
`string[] password = new string[1000];`
1000 becaus i dont know where get the define MAX_PLAYERS;
`password[player.Id] = inputtext;`

are you have the most rationality method this implementation?example please.

**Comment by tiuman** [comment]
second question why not worked this menu.. i see menu but i cant select rows. 


 private void dialog_pass_cheked(object sender, DialogResponseEventArgs e)
 {
                Vector2 sss = new Vector2(50,200);
                Menu menu = new Menu("Select skin",sss);
                menu.Columns.Add(new MenuColumn(200));
                menu.Rows.Add(new MenuRow("next"));
                menu.Rows.Add(new MenuRow("prev"));
                menu.Rows.Add(new MenuRow("select"));
                menu.Show(e.Player);
                menu.Exit += (o, eventArgs) =>
                {
                    e.Player.SendClientMessage("MENU CLOSED");
                    menu.Dispose();
                };

                menu.Response += (o, eventArgs) =>
                {
                    e.Player.SendClientMessage("SELECTED ROW " + eventArgs.Row);
                    menu.Dispose();
                };
}

**Comment by ikkentim** [comment]
You seriously need to look into what object oriented programming is. This is basic c# knowledge.
