### ISSUE TITLE
how organization work?

### ISSUE THREAD

**Issue by tiuman** [ikkentim/SampSharp#181]
i create class of user data. and if player connect create instance of class user data and add this object in object[] with index playerid?

**Comment by ikkentim** [comment]
Inherit from BasePlayer and store your values in there

``` c#
[PooledType] // Indicate this class overrides the default BasePlayer class
public class Player : BasePlayer
{
    // store custom values in custom properties
    public string MyCustomData { get; set; }
    public int MoreOfMyCustomData { get ;set; }

    // or store it in a separate info class ( very useful, as it can be serialized/stored to a db like this )
    public PlayerInfo Info { get; set; }
}
```

If at any point you receive a BasePlayer instance, you can simply cast it to Player to access your own custom data ( `player as Player`)

**Comment by tiuman** [comment]
how each user is assigned a class instance?

**Comment by tiuman** [comment]
how to get data from property "MyCustomData", iside mode?

**Comment by ikkentim** [comment]
Instances of this class are automatically created by sampsharp when a player joins. Same goes for vehicles (BaseVehicle class) and other types.

**Comment by tiuman** [comment]
cool

**Comment by tiuman** [comment]
i am sorry but how the get this properties classes, from within another class?

**Comment by tiuman** [comment]
protected override void OnPlayerConnected(BasePlayer player, EventArgs e)
        {
            playerInst pl_inst = (player as PlayerPooled).playerInstance;
            sql_read sql = new sql_read();
            player.ToggleSpectating(true);
            NpgsqlDataReader dd =  sql.sql_in("SELECT pass,id FROM samp2.user WHERE name='"+player.Name.ToLower()+"'");
            if (dd.HasRows)
            {
                while (dd.Read())
                {
                    InputDialog login = new InputDialog("Логин", "Введите пароль", false, "OK", "");
                    (player as PlayerPooled).playerInstance.temp_pass = dd.GetString(0);
                    login.Show(player);
                    login.Response += Login_Response;
                }
            }
            else
            {
                InputDialog registration = new InputDialog("Регистрация", "Введите пароль", false, "OK", "");
                registration.Show(player);
                registration.Response += reg_dialog;
            }
            sql_init.conn.Close();
        }




[PooledType]
    class PlayerPooled : BasePlayer
    {
        playerInst playerInstance { get; set; }
    }

    class playerInst
    {
        public string temp_pass;
        public int sql_playerid;
        public string email;
        public string referal;

        System.Threading.Timer myTimer;
        string text;
        int ping_wait_koeficient;
        public void kick_tm(int timeout, int ping_wait_koeficient, string text, BasePlayer player)
        {
            this.ping_wait_koeficient = ping_wait_koeficient;
            this.text = text;
            TimerCallback das = new TimerCallback(kick_with_subscribe);
            myTimer = new System.Threading.Timer(das, player, 1000 * timeout, 0);

        }
        void kick_with_subscribe(object state)
        {
            BasePlayer dd = (BasePlayer)state;
            dd.SendClientMessage(Color.Red, text);

            TimerCallback das = new TimerCallback(kick_with_timeout);
            System.Threading.Timer myTimer = new System.Threading.Timer(das, dd, dd.Ping * ping_wait_koeficient, 0);
        }

        void kick_with_timeout(object state)
        {
            BasePlayer ss = (BasePlayer)state;
            ss.Kick();
        }
        public void disp()
        {
            myTimer.Dispose();
        }
    }
