### ISSUE TITLE
how to make sure that the OnPlayerRequestClass returns 0

### ISSUE THREAD

**Issue by tiuman** [ikkentim/SampSharp#183]
how to make sure that the OnPlayerRequestClass returns 0, if OnPlayerRequestClass returned 0 then press buttons is be not handled... 

public OnPlayerRequestClass(playerid, classid)
{
	return 0;
}

**Comment by ikkentim** [comment]
Check the event args
http://api.sampsharp.timpotze.nl/html/72bd09db-69b8-2bb3-68da-c9225b437ec4.htm
