### ISSUE TITLE
how the catch bugs if server console closes without crash data in file server_log.txt

### ISSUE THREAD

**Issue by tiuman** [ikkentim/SampSharp#185]

**Comment by ikkentim** [comment]
It might be a sampsharp bug :( try to find out what you were doing when it crashed, try to reproduce it, and then report it here.

**Comment by tiuman** [comment]
it's crashed when i taran gate in zona 51 where airport on vehicle model 495. 
but not always.:(

**Comment by tiuman** [comment]
same problem the has been by other people uses sampsharp. or i not right configure my server. i configuring them step by step from instruction. this happened when i playin in server randomize 1-2 pcs per day.
sampsharp is not recomendet for use a public server?

**Comment by tiuman** [comment]
or only i get same problem ?

**Comment by tiuman** [comment]
somebody make done  public server uses sampsharp? and work it without crashes? max uptime

**Comment by ikkentim** [comment]
I've not seen anything similar happen with other people. Entering a specific area cannot crash a server and spawning a vehicle has been tested many times. it must be something else you are doing. Could you be more specific?

There are currently no public servers yet using sampsharp, but I think someone said he's pushing for starting a server soon, he has so far had no issues with sampsharp.

**Comment by fvandillen** [comment]
I have had a server running for days on end, without any issues. Could you be more specific regarding your bug?

**Comment by tiuman** [comment]
Maybe it seemed to me or there were obviously some bad things in the code. Who initiated this error, but since that time until now, not a single bug has been beaten.
