### ISSUE TITLE
Server crashed using System.Reflection

### ISSUE THREAD

**Issue by NewbProgramming** [ikkentim/SampSharp#186]
Using the System.Reflection library the server crashed when I created an empty object array and tried to pass it through MethodInfo.Invoke.

```
object[] parameters = new object[0]; // object[] parameters = new object[GetType().GetMethod("RCON_client").GetParameters().Length]

// Populate parameters object here.

GetType().GetMethod("RCON_client").Invoke(instance, parameters);
```

The command did what I intended it to, it invoked the method and asked if I wanted to start the client.
But it crashed right after displaying the debug message.

https://files.slack.com/files-pri/T2GBFD48G-F4AR99W23/pasted_image_at_2017_02_24_09_37_am.png

**Comment by ikkentim** [comment]
My bad...
