### ISSUE TITLE
how give the cyrillic symbols from samp console 

### ISSUE THREAD

**Issue by tiuman** [ikkentim/SampSharp#190]
example /cmd Привет. 
system thinking as /cmd null.
in config file have field string cp1251

**Comment by ikkentim** [comment]
As far as I know it should work just fine... 

In the config you should have "codepage cp1251"

**Comment by tiuman** [comment]
![sa-mp-008](https://cloud.githubusercontent.com/assets/5276681/24452385/feaa571c-14bd-11e7-859c-2d4af8199239.png)
![sa-mp-009](https://cloud.githubusercontent.com/assets/5276681/24452388/02584810-14be-11e7-9058-ef988ae2bf7c.png)
![sa-mp-003](https://cloud.githubusercontent.com/assets/5276681/24452392/084fe3ea-14be-11e7-9f46-95b5084ed43b.png)
![sa-mp-005](https://cloud.githubusercontent.com/assets/5276681/24452397/0d472dd6-14be-11e7-8fd4-76ccd3f51035.png)
![default](https://cloud.githubusercontent.com/assets/5276681/24452414/1dbbf84a-14be-11e7-9889-5d89dacde77b.png)

**Comment by ikkentim** [comment]
Hmm... Interesting... 

Maybe @5LICK has some insights? It worked for you, right?

**Comment by 5LICK** [comment]
@ikkentim Yes but i tried to repeat this case (text for command), and when i using russian letters, i don't see them.
If type text `Test привет` in the chat, then i will see only `Test`, without russian word.
In general if send russian text directly, all works fine.

**Comment by ikkentim** [comment]
Hmm, interesting... If you print the received message to the server console, does that work?

**Comment by tiuman** [comment]
![111111](https://cloud.githubusercontent.com/assets/5276681/24553758/399a3cb2-1666-11e7-98cb-7f9456901c76.png)

**Comment by tiuman** [comment]
![sa-mp-011](https://cloud.githubusercontent.com/assets/5276681/24553914/c96986e0-1666-11e7-98f5-1cf30d352372.jpg)

**Comment by tiuman** [comment]
![111](https://cloud.githubusercontent.com/assets/5276681/24554116/6503e15e-1667-11e7-8471-67a319a3b63c.png)

**Comment by ikkentim** [comment]
Thanks! I'll investigate

**Comment by MatvienkoDO** [comment]
Same problem also exists in dialogs

![screenshot_1](https://user-images.githubusercontent.com/15823938/29274838-388e4fd8-811a-11e7-9e5d-fbe0512550ab.png)
![screenshot_2](https://user-images.githubusercontent.com/15823938/29274842-3af5f226-811a-11e7-8be2-869cf0717490.png)
![screenshot_3](https://user-images.githubusercontent.com/15823938/29274846-3e616242-811a-11e7-9e46-a6a381ddbb8c.png)
![screenshot_4](https://user-images.githubusercontent.com/15823938/29274848-4140b59e-811a-11e7-8b01-7addfdde3762.png)
![screenshot_5](https://user-images.githubusercontent.com/15823938/29274852-4385551c-811a-11e7-8928-365cf949b1dd.png)
![screenshot_6](https://user-images.githubusercontent.com/15823938/29274855-45507354-811a-11e7-8e40-8dfd656feb8f.png)
![screenshot_7](https://user-images.githubusercontent.com/15823938/29274857-47dc758c-811a-11e7-9138-8661f8e21d67.png)

**Comment by ikkentim** [comment]
It probably happens anywhere where text is displayed. I'm hoping to have a beta for v0.8 ready soon after my vacation.

**Comment by ikkentim** [comment]
I mean, anywhere text can be entered

**Comment by ikkentim** [comment]
This should be fixed in the newly released 0.8.0-alpha1 version. Please note this is a prerelease that should not yet be used on a production/public server.
