### ISSUE TITLE
please give me small tutorial create pickup

### ISSUE THREAD

**Issue by tiuman** [ikkentim/SampSharp#192]
```
                Vector3 ssr = new Vector3(xe, ye, ze);

                var ss = Pickup.Create(modelid,3,ssr,player.VirtualWorld);
                ss.PickUp += Ss_PickUp;


        private void Ss_PickUp(object sender, PlayerEventArgs e)
        {
         WHERE GET THE ID???   
        }
```
How to assign an id and how to see it in an event?
i want know which pickup is  pickupped?

**Comment by fvandillen** [comment]
You can simply store the reference to ```ss``` somewhere. In a 
```System.Collections.Generic.List``` for example.

tiuman wrote:

**Comment by tiuman** [comment]
And?? with what is compare within event?

**Comment by 5LICK** [comment]
In your case, method `Ss_PickUp` will perform for your pickup `ss`. You not need use pickup id, that is doing SampSharp.

**Comment by tiuman** [comment]
i uderstand ... thnks
