### ISSUE TITLE
For what need a controllers? 

### ISSUE THREAD

**Issue by tiuman** [ikkentim/SampSharp#195]

**Comment by eXeGOODER** [comment]
<details><summary>image from wiki</summary>

![image](https://cloud.githubusercontent.com/assets/6906042/25064755/636fded8-221a-11e7-8cd5-b3188eda7106.png)
</details>

**Comment by tiuman** [comment]
i am has read it but not understand why it need?

**Comment by fvandillen** [comment]
Simple: to handle events.

**Comment by tiuman** [comment]
@fvandillen handling events with it example.
`protected override void OnPlayerPickUpPickup(Pickup pickup, PlayerEventArgs e)`
not true?

**Comment by ikkentim** [comment]
Controllers are one way of splitting your gamemode up into different modules. Using controllers you can easily hook onto different events, register new types or register new services. Controllers are mostly optional and fully customizable.
