### ISSUE TITLE
what it be?

### ISSUE THREAD

**Issue by tiuman** [ikkentim/SampSharp#196]
description get from postgresql 
SHOW client_encoding;
 client_encoding
-----------------
 WIN1251

![default](https://cloud.githubusercontent.com/assets/5276681/25113699/379c022a-2434-11e7-99a8-626261a4c84c.png)

string str = string.Format("{{FFFFFF}}Класс: Мед. \nНаименование: {0}\nУровень {{05ecff}}{1}{{FFFFFF}}\nКоличество: {2}\nКачество исполнения: {3}\nЕдениц здоровья: {4}+{{05ecff}}{10}{{FFFFFF}}\nКровоостанавливающий эффект: {5}\nВосстанавливает сломанные кости: {6}\nПротивовоспалительный эффетк: {7}\nАнтидод от нервнопаралитиеских веществ: {8}\nЕденица регенерации: {12}\nПродолжительность рененерации: {13}\nОписание: {11}\nМастер: {9}", ssf[1], ssf[5], ssf[2], ssf[3],ss[1], bbool(ss,4), bbool(ss,5), bbool(ss,6), bbool(ss,7),ssf[6].ToString(), lvl,ss[8].ToString(), ss[2].ToString(), ss[3].ToString());

**Comment by ikkentim** [comment]
You are probably saving it escaped in your database. This is not related to sampsharp.
