### ISSUE TITLE
Check if the server doesn't permanently hang in Dialog.ShowAsync if the player leaves

### ISSUE THREAD

**Issue by ikkentim** [ikkentim/SampSharp#199]

**Comment by SnowDog4822** [comment]
Have there been any updates on this issue being addressed? I am having a problem where one Task awaiting a Dialog.ShowAsync response is actually completely hanging up a completely separate Task.

**Comment by ikkentim** [comment]
This has not been resolved yet :/ , expect it in the next alpha

**Comment by ikkentim** [comment]
It didn't hang, but change exception from TaskCancelledException to PlayerDisconnectedException.
