### ISSUE TITLE
OnPlayerKeyStateChanged

### ISSUE THREAD

**Issue by tiuman** [ikkentim/SampSharp#201]
if (e.NewKeys == Keys.Walk)
{
      Console.WriteLine("Alt will pressed");
}
it code work only if single key press if press multiple example RMB and ALT it code not work..
How right write code what be sens a multiple press key example 
SPACE+ALT 
SPACE+Y+ALT 
N+ALT
H+ALT
if (e.NewKeys == Keys.Walk)
{
      Console.WriteLine("Alt will pressed");
}

**Comment by eXeGOODER** [comment]
KeyUtils:
http://api.sampsharp.timpotze.nl/html/f45e7113-e51f-5d71-4e1d-261f3136fedc.htm
