### ISSUE TITLE
Not working a breakpoint

### ISSUE THREAD

**Issue by swedays** [ikkentim/SampSharp#204]
Hello. not working a breakpoint. 
“The breakpoint will not currently be hit. No symbols have been loaded for this document.”
It is possible as that to correct?
Thanks!
![1](https://cloud.githubusercontent.com/assets/28545496/25825100/54589e2a-344a-11e7-8201-4c36771bad89.jpg)

**Comment by ikkentim** [comment]
For 0.7.x, you can't currently use the debugger. This will change for the next update, v0.8.

**Comment by ikkentim** [comment]
A prerelease of 0.8 has been released, which supports debugging. Please note it is a prerelease and should not be used in a production environment.
