### ISSUE TITLE
Some codes doesn't exist in the Rivershell and GrandLarg here... 

### ISSUE THREAD

**Issue by Tagoff** [ikkentim/SampSharp#207]
Hello everyone,
Some codes of Rivershell and GrandLarg is missing here, where could i found it? the rest code works but not whole.
I tried to resolve with the NuGet SampSharp updating to the last version file but nothing yet ... 

http://imgur.com/ZWUDupZ

> SetWeather ( Method )
SetWorldTime ( Method )
GtaVehicle ( Class? )
LetterHeight ( TextDraw )
LetterWidth ( TextDraw )
GtaPlayer ( Class? )
OnConnected
OnSpawned
OnDeath
SetSkillLevel
GiveWeapon
ToggleClock
ResetMoney
ETC... A LOT But not the whole method's and codes.

**Comment by ikkentim** [comment]
Ah yea, those samples were written for SampSharp 0.6.2, I'll need to update them... Thanks for letting me know 👍

**Comment by Tagoff** [comment]
OK.
How could i call the OnConnect ( or some other ) in other class without be the mainly game-mode class?
I created a Library Class with the name "Connection.cs" and in this class i referenced the BaseMode class and call the Protection override OnPlayerConnection bellow:

````
class Connection : BaseMode
    {
        protected override void OnPlayerConnected(BasePlayer player, EventArgs e)
        {           
            base.OnPlayerConnected(player, e);
            Console.WriteLine(player.Name + " connected the server with the ID number: " + player.Id + " ( IPAddress: " + player.IP + " )");
            player.GameText("Test test test", 30000, 3);
        }
    }`

```

**Comment by ikkentim** [comment]
For every callback there's an event available:

```
class Connection
{
    public Connection(BaseMode gameMode)
    {
        gameMode.PlayerConnected += OnPlayerConnected;
    }

    private void OnPlayerConnected(object sender, EventArgs e)
    {
        BasePlayer player = sender as BasePlayer;
        // ...
    }
}
```

**Comment by Tagoff** [comment]
Thanks again.
But where do i put the new object reference Connection? i'm not finding any place with pass BaseMode parameter to use.

`Connection PlayerConnection = new Connection( /* BASE MODE VAR. */ );`

**Comment by ikkentim** [comment]
I'm getting the feeling you're structuring your gamemode a little wrong, try check out the examples. If you override the player class (see example below), it is a nice place to start hooking up events from


```
[PooledType] // Indicate to use this class instead of default
class Player : BasePlayer
{
    protected override OnConnected(EventArgs e)
    {
        base.OnConnected(e);
    }
}

**Comment by Tagoff** [comment]
Sorry but i still no understood.
I have two classes, one is the main class ( GameMode.cs ) and other is the class of the player connections ( Connection.cs ) is related by enter and exit connections, the main class is called because i put it in the Server.cfg but what i didn't understand is how could i call the Connection.cs to the server and use the event handler OnPlayerConnected... because the Connection.cs isn't referenced to be call by server and i don't find enough parameters to put it in the Main class.

```
// Main class.
protected override void OnInitialized(EventArgs e)
{
 base.OnInitialized(e);
}

protected override void LoadControllers(ControllerCollection controllers)
{
 base.LoadControllers(controllers);
}

// Connection.cs
// The OnPlayerConnection in Connection.cs isn't called by the server, why?

namespace MyGamemode
{
    class Player : BaseMode
    {

        public Player(BaseMode eventHandler)
        {
            eventHandler.PlayerConnected += OnPlayerConnected;
        }

        protected void OnPlayerConnected(object sender, EventArgs e)
        {
            BasePlayer playerid = sender as BasePlayer; 
            Console.WriteLine($":EVENT HANDLER: Player {playerid.Name} connected ID: {playerid.Id} ( IPAddress: {playerid.IP}");

        }
    }
}

```
 Where do i reference to the server call the connection.cs event?

**Comment by ikkentim** [comment]
Do NOT make anything but a gamemode class inherrit from BaseMode. Let your player class inherrit from BasePlayer, as I showed you in the example code in my previous comment.

**Comment by ikkentim** [comment]
What might also be useful for you is controllers:
```
[Controller]
class ConnectionsController : IController, IEventListener
{
    public virtual void RegisterEvents(BaseMode gameMode)
    {
        gameMode.PlayerConnected += OnPlayerConnected;
    }

    private void OnPlayerConnected(object sender, EventArgs e)
    {
        BasePlayer player = sender as BasePlayer;
        // ...
    }
}
```
