### ISSUE TITLE
Possible bug with e.PreventSpawning from RequestSpawn.

### ISSUE THREAD

**Issue by Tagoff** [ikkentim/SampSharp#210]
I put in OnInicializes all PlayerClasses that I would like to be selected in RequestClass, but now witch e.PreventSpawning, the selection doesn't work, no one skin change but the coordinates still working...

`               
                //OnInicialized.
                
                AddPlayerClass(77, new Vector3(256.0815, -43.0475, 1004.0234), 270f);

                AddPlayerClass(78, new Vector3(256.0815, -43.0475, 1004.0234), 270f);

                AddPlayerClass(79, new Vector3(256.0815, -43.0475, 1004.0234), 270f);

                AddPlayerClass(134, new Vector3(256.0815, -43.0475, 1004.0234), 270f);

                AddPlayerClass(135, new Vector3(256.0815, -43.0475, 1004.0234), 270f);

                AddPlayerClass(137, new Vector3(256.0815, -43.0475, 1004.0234), 270f);

                AddPlayerClass(212, new Vector3(256.0815, -43.0475, 1004.0234), 270f);

                AddPlayerClass(230, new Vector3(256.0815, -43.0475, 1004.0234), 270f);

                AddPlayerClass(239, new Vector3(256.0815, -43.0475, 1004.0234), 270f);`

```
private void SelecionarSkin(object sender, SampSharp.GameMode.Events.RequestClassEventArgs e)
        {           
            BasePlayer playerid = sender as BasePlayer;
            //
            playerid.Position = PlayerPos;
            playerid.Interior = Pinterior;
            playerid.CameraPosition = CameraPos;
            playerid.SetCameraLookAt(CameraLookAt);

            e.PreventSpawning = true; // This doesn't allow me to select any skin and the skin default is 0 being that i didn't put the CJ Skin and it was to prevent spawning only !! 
        }
```

**Comment by ikkentim** [comment]
Setting PreventSpawning to true basically returns 0 here http://wiki.sa-mp.com/wiki/OnPlayerRequestClass
