### ISSUE TITLE
Dialog.Hide is not working

### ISSUE THREAD

**Issue by Syntheq** [ikkentim/SampSharp#212]

**Comment by Syntheq** [comment]
But I found a solution like that
`            var native = Native.Load("ShowPlayerDialog", typeof(int), typeof(int), typeof(int), typeof(string), typeof(string), typeof(string), typeof(string));
            native.Invoke(player.Id, -1, 0, " ", " ", " ", " ");
`

**Comment by ikkentim** [comment]
Hmm maybe it isn't working because I use empty strings instead of a single space... I'll fix that for the next version

**Comment by ikkentim** [comment]
This has been fixed for the next 0.8.0 alpha. Thanks for reporting the issue!
