### ISSUE TITLE
How to use and run server with SampSharp 0.8.0-alpha

### ISSUE THREAD

**Issue by eXeGOODER** [ikkentim/SampSharp#216]
Sorry, but documentation not completed? Or i doing something wrong?
<details>
<summary>Server console</summary>

![image](https://user-images.githubusercontent.com/6906042/30249981-8741b934-9660-11e7-8a9b-8aecf8837217.png)
</details>
<details>
<summary>Server config</summary>

![image](https://user-images.githubusercontent.com/6906042/30249991-c8bf9548-9660-11e7-9a0e-570e4443b2d9.png)
</details>

**Comment by ikkentim** [comment]
Starting v0.8, SampSharp runs in a separate process (not in the SA-MP server process). You have to create a new C# Console Application project, in which you can add your game mode code. The entry point of your console application (Program.Main) should look like:
```
        static void Main(string[] args)
        {
            new GameModeBuilder()
                .Use<GameMode>()
                .Run();
        }
```

If you now launch your new console application and the sa-mp server, everything should now work.

**Comment by ikkentim** [comment]
Please note: the gamemode, symbols and codepage options are no longer required. If you wish to use a custom encoding, please see http://alpha.sampsharp.timpotze.nl/gamemode-builder#encoding (please note this documentation website is under construction)

**Comment by eXeGOODER** [comment]
<details>

![image](https://user-images.githubusercontent.com/6906042/32144127-ca7a9a9a-bcd5-11e7-948e-394f7dd644e9.png)
</details>
<details>

![image](https://user-images.githubusercontent.com/6906042/32144136-f64b0a4c-bcd5-11e7-9611-7dc7b3f0dec9.png)
</details>

**Comment by oxsotus** [comment]
Run SAMP server and your GameMode application with administrator rights.
