### ISSUE TITLE
OnPlayerCommandText not support cyrillic 

### ISSUE THREAD

**Issue by sentik** [ikkentim/SampSharp#218]
Hi, I made a command that takes text. If I specify the text in English, then everything is ok. If I specify the text in Russian, then the text is empty. I decided to test the problem in "internal bool OnPlayerCommandText (int playerid, string cmdtext)", the result is cmdtext = null;

Text in dialog boxes, chat, console is not displayed correctly.
SampSharp v7.

/me Hello
/me Привет

> gamemode Suncity:WorldGameMode
> symbols SampSharp.GameMode.dll SampSharp.Streamer.dll Suncity.Models.dll Suncity.dll 
> codepage cp1251
> 
> plugins streamer SampSharp

**Comment by sentik** [comment]
In the call **MonoString* GameMode::StringToMonoString(char* str, int len)** , text is exist

**Comment by ikkentim** [comment]
This has been fixed in 0.8.0, see #190
