### ISSUE TITLE
Threading issues after calling SA-MP natives

### ISSUE THREAD

**Issue by SnowDog4822** [ikkentim/SampSharp#220]
When attempting to use `await` in the current 0.8.0-alpha1 release on .NET Core 2.0 the method will not proceed past the await or complete. I tested this on both my own game mode and @ikkentim's TestMode. In both cases, any method using await will not complete.

When testing the TestMode in particular, this issue arose both with the `/dialogtest` command as well as a simple command that I wrote for testing purposes.

This command:
```csharp
        [Command("testawait")]
        public static async void testAwait(BasePlayer player)
        {
            Console.WriteLine("Waiting 2 seconds...");

            await Task.Delay(2000);

            Console.WriteLine("Success!");
        }
```

resulted in only the `Waiting 2 seconds...` line being printed. The success message never printed.

I am unsure if this only affects .NET Core or .NET Core 2.0 in particular.

**Comment by ikkentim** [comment]
It works for me 🤔 

```
Waiting 2 seconds...
Success!
```

Used your code on a fresh, .NET Core 2.0 project

**Comment by SnowDog4822** [comment]
I believe that I have made an important breakthrough in this issue. I have been rigorously testing the fresh .NET Core TestMode server the past hour and I finally came across something. The game mode appears to, most of the time, not start up properly.

**SCENARIO A**
Roughly 9/10 times, the game mode starts up and the console and the `/testawait` command (see original post for source) looks like this:
![](https://i.imgur.com/SRbSra4.png)
![](https://i.imgur.com/YJD2XlU.png)

**SCENARIO B**
However, I noticed that every once and a while, when I start the game mode up, the console and `/testawait` command looks like this:
![](https://i.imgur.com/Izi7Vig.png)
![](https://i.imgur.com/9MD0szg.png)

What do you notice about these screenshots? In scenario A, the one I experience the most frequently, you can see that custom rcon commands do not register and display in the console, and the await in the test command does not work properly. However, in scenario B, you can see that the game mode seems to initiate *properly*. You see that rcon commands register and log to the console properly, and awaits work perfectly.

There is absolutely no difference in the environment or source code between these two scenarios. It seems to be totally random and a "hit or miss" situation. I just start up the server and hope it works properly, and most of the time it does not.

Some other various observations that I've made during testing:
- Testing was done using the latest alpha2 release (although for some reason it still displays as alpha1 when the SA-MP plugin loads in samp-server.exe.
- The await that you placed in the TestMode.OnInitialized always works properly, regardless of the scenario. Only subsequent awaits do not function properly. You can see an example of this in screenshots of both scenarios above.

To conclude, I essentially seem to be getting an inconsistency when I start the server. I also tried changing the order that I started both executables in (dotnet, samp-server.exe <=> samp-server.exe, dotnet) and it doesn't seem to matter. It's completely random whether or not the server functions properly or not.

I did not originally realize this was the issue because the server had actually never started properly for me. It wasn't until I randomly saw the rcon commands register in the server console that I realized the awaits were then working properly and that something was wrong with the server *most* of the time.

**Comment by SnowDog4822** [comment]
I know I've already contacted you about this in Slack, but for the record I'll update this issue. This is apparently some sort of threading problem somewhere in the `SampSharp.Core.Threading` either with the `MessageQueue` or `MessagePump` and it can be reproduced by calling a native (such as `SetGameModeText()`) anywhere in the gamemode and then attempting to use async/await afterwards. Once the native has been called, it has a random chance (it doesn't reproduce 100% of the time) of hanging up all future asynchronous methods in the SampSharp server.
