### ISSUE TITLE
Kick a player -> server crash

### ISSUE THREAD

**Issue by oxsotus** [ikkentim/SampSharp#223]
Hi!

When I want to kick a player the server immediately stops.
There are any tricks, how to kick a player?
I tried to kick a player delayed (1 seconds), and I kick inside OnTick event, it crashes.
After I tried to kick when the player connect, but it crashes too.

Here's the crash log, there are no more info about that.
https://pastebin.com/1TsHf996

**Comment by ikkentim** [comment]
Is this in 0.8?

**Comment by oxsotus** [comment]
Yes, 0.8.0 - alpha2

**Comment by ikkentim** [comment]
Just FYI, I've reproduced it and am looking for a way to fix it.

**Comment by ikkentim** [comment]
Fixed in f2fd2f692fed7fb6b70223c8b212b2586ef18efe
