### ISSUE TITLE
Player Class.

### ISSUE THREAD

**Issue by Tagoff** [ikkentim/SampSharp#224]
Let's say I would like to create a Player Class, where there are all your variables, what the best way to do that? and, if i need to call the class, what the best way to call it? with a List?

```
// How could i call, the ID 21?
List<PlayerVar> players = new List<PlayerVar>();
// To add.
players.insert()...; // ??
// To remove.
players.remove() ..; // ??

// Player Class
public class PlayerVar : IDisposable
{
  public BasePlayer playerid = null;

   public int Level = 0;
   public int Money = 0;

   public PlayerVar(BasePlayer playerid, int Level, int Money)
   {
      this.playerid = playerid;
      this.Level = Level;
      this.Money = Money;
   }
}
```

**Comment by SnowDog4822** [comment]
The best way to handle this is to extend the `BasePlayer` controller and register your own controller. For example, I made a class called Player and extended the `BasePlayer` controller. Within the Player class, I have several other objects that hold the players data from the database as well as other temporary variables. This way, when the player disconnects, everything is disposed of properly without me needing to worry about it. You also do not need to store them in a list as the controller will take care of that for you. You can access all players by using `BasePlayer.All`.

See this article for more details: http://sampsharp.timpotze.nl/controllers

**Comment by Tagoff** [comment]
This way?
`class PlayerControllerOverride : BasePlayerController
    {
        public override void RegisterTypes()
        {
            Player.Register<Player>();
        }
    }

    class Player : BasePlayer
    {
        public int Level = 0;
    }`

**Comment by ikkentim** [comment]
You actually don’t need to use your custom controller since 0.7, you can simply use

[PooledType] class Player : BasePlayer { }

**Comment by Tagoff** [comment]
One thing i still didn't undestand is how could i call the class by the Player ID...

In the Player Class has a PlayerStyle enum variable, i used it to define if the player is in Login, Registering etc.

`    [PooledType]
    class Player : BasePlayer
    {
        public int Level = 0;
        public PlayerStyle PlayerMode;


        public Jogador(PlayerStyle PlayerMode)
        {
            this.PlayerMode = PlayerMode;
        }
    }`

In this way, i can use it to check if he can use CMD's or chating, but, how could i use the class by the ID?

`private void ChatPlayerSended(object sender, SampSharp.GameMode.Events.TextEventArgs e)
 {
   if(Player ..ID.. .PlayerMode == PlayerMode.Loging) return;
 }`

**Comment by ikkentim** [comment]
You can cast instances of BasePlayer to Player.

**Comment by Tagoff** [comment]
Sorry again rs
How?

Player id = BasePlayer as Player; 
??

**Comment by ikkentim** [comment]
Example
```
[PooledType]
class Player : BasePlayer 
{
    public void DoWhateverYouWant(){}
}

class GameMode : BaseMode
{
    protected override void OnPlayerConnected(BasePlayer player, EventArgs e) 
    {
        base.OnPlayerConnected(BasePlayer player, EventArgs e);
        Player myPlayer = player as Player;

        myPlayer.DoWhateverYouWant();
    }
}
```

**Comment by Tagoff** [comment]
Thank you !
