### ISSUE TITLE
Cast between to objects

### ISSUE THREAD

**Issue by Tagoff** [ikkentim/SampSharp#226]
When do I know it is for use the AS Keyword ? i mean, how could i know that a object is valid to use it? Example:
I have two classes, the first is the BasePlayer and the secound is the User, if i would to get the BasePlayer as parameter but in User class, how will it valid?
Because it's very hard to get the ID from the User class, because in the user class that have the whole variables.

I'm also tried to understand, creating some stuff in Console Application but, nothing yet

```
            BasePlayer playerid = new BasePlayer();
            User user = playerid as User;
            if (user == null) Console.WriteLine(":: Null !");
            else // Not null
            {
                user.level = 12; //Only a example. 
            }
```

**Comment by oxsotus** [comment]
You can't cast it.
BasePlayer isn't inherited User.
If User inhetired BasePlayer it won't work too, because you get the simple BasePlayer not which is casted to BasePlayer from User.
Use dictionary.

**Comment by ikkentim** [comment]
See #224 .
