### ISSUE TITLE
PlayerTextDraw's 

### ISSUE THREAD

**Issue by Tagoff** [ikkentim/SampSharp#230]
How can I send an ID to a Textdraw Player? I know how, it was working BUT when I used SandBox to see if it was really going, the player in question did not receive it, only one that had nothing to do with the story.

I have separated all contents in Class, the PlayerTextdraw's creation is by the PlayerTextDraw_Servidor by a Method, that it receives a BasePlayer usuario. 

>  public static CreatePlayerTextDraw(BasePlayer usuario)
> {
> TutorialLabel = new PlayerTextDraw(usuario, new Vector2(322.916595, 155.777740), " ", SampSharp.GameMode.Definitions.TextDrawFont.Normal);
>             TutorialLabel.LetterSize = new Vector2(0.400000, 1.600000);
>             TutorialLabel.Width = 0.000000F;
>             TutorialLabel.Height = 427.000000F;
>             TutorialLabel.Alignment = SampSharp.GameMode.Definitions.TextDrawAlignment.Center;
>             TutorialLabel.UseBox = true;
>            TutorialLabel.Proportional = true;
>            TutorialLabel.BoxColor = 102;
> }

When i use the Show method, how could i now if the ID X will receive?

> PlayerTextDraw_Servidor.TutorialLabel.Show();

**Comment by ikkentim** [comment]
Please forget about ids, sampsharp allows you to work in an Object-Oriented manner. You simply need the reference to the player and call `textDraw.Show(player);`.

**Comment by Tagoff** [comment]
So should I take advantage of a class that already has an object, which references a BasePlayer class?

**Comment by ikkentim** [comment]
You could do that. If you're just showing the text draw to a single player, you might as well use `PlayerTextDraw` instead.
