### ISSUE TITLE
How to create a command?

### ISSUE THREAD

**Issue by Tagoff** [ikkentim/SampSharp#231]
I have found in the Wiki and GrandLarg, but i didn't understand.

The command Kill, how does it call the KillMe? how to use the [Command("example")] to call a method? 
>         [Command("kill")]
>         public static void KillMe(BasePlayer player)
>         {
>             player.Health = 0.0f;
>         }

in my case I need to create one that supports many parameters.

**Comment by WopsS** [comment]
Hello,

That's called an attribute (https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/attributes). Also take a look in **TestMode.DotNetCore** (https://github.com/ikkentim/SampSharp/blob/master/src/TestMode.DotNetCore/GameMode.cs#L35-L39) for multiple parameters.

**Comment by ikkentim** [comment]
Your code is scanned by sampsharp when the gamemode starts. It'll look for all [Command] attributes and create commands based of the methods it finds.

**Comment by Tagoff** [comment]
Thanks !
I will study more about it.
