### ISSUE TITLE
Writing anticheat

### ISSUE THREAD

**Issue by EmanOK** [ikkentim/SampSharp#235]
I so understand anti-cheat it will not turn out to write. For example, on OnVehicleMod, you can not return 0 to desync the component (preventing players from out).
Is there a solution?

**Comment by ikkentim** [comment]
Set PreventPropagation to true http://api.sampsharp.timpotze.nl/html/a1a4205a-a941-c312-9cc1-a1106f7719d9.htm

**Comment by EmanOK** [comment]
Wow, something not noticed it. Thank you
