### ISSUE TITLE
Gamemode does not work on pre-release versions

### ISSUE THREAD

**Issue by EmanOK** [ikkentim/SampSharp#236]
The gamemode does not work, but the server is running.
http://prntscr.com/htenjk
When connected to the server, [he restarting ](http://prntscr.com/htf1gg)or not responding

Installed like a release, why does not it work? Tried and net.core and net.standart libs

**Comment by ikkentim** [comment]
You need to both start the sa-Mp server and the sampsharp (.net) server

**Comment by EmanOK** [comment]
What do you mean by sampsharp server?

**Comment by ikkentim** [comment]
I'm sorry, did you figure it out yet? In 0.8, the game mode runs in a separate process, therefore you should turn your game mode project into a console application which you should start alongside your sa-mp server. Proper documentation will be available later.

During game mode development you can keep the sa-mp server running while only restarting the game mode server to update it.

**Comment by EmanOK** [comment]
So here's the thing. Now I was able to run the game mode.
```csharp
    class Program
    {
        static void Main(string[] args)
        {
            SampSharp.Core.GameModeBuilder gameMode = new SampSharp.Core.GameModeBuilder();
            gameMode.Use<GameMode>();
            gameMode.Run();
            Console.ReadLine();
        }
    }

    class GameMode : SampSharp.GameMode.BaseMode
    {
        protected override void OnInitialized(EventArgs e)
        {
            base.OnInitialized(e);
            Console.WriteLine("It is great");
        }
    }
```
