### ISSUE TITLE
Calling a native

### ISSUE THREAD

**Issue by EmanOK** [ikkentim/SampSharp#243]
Hello.  How can I call native?
This documentation is not suitable for the pre-release version http://sampsharp.timpotze.nl/natives#introduction
I came only to this decision:
```csharp
            var native = SampSharp.Core.InternalStorage.RunningClient.NativeLoader.Load("GetPlayerCustomSkin", new NativeParameterInfo[] { NativeParameterInfo.ForType(typeof(int))});
            return native.Invoke(Id);
```
I had to change the modifier of access to InternalStorage on public.
Or is it possible to do it differently?

**Comment by d0Nt** [comment]
You could try 
`[NativeMethod]
public int GetPlayerCustomSkin(int playerId)
{}`

**Comment by EmanOK** [comment]
Ohhh, for sure! How could I have forgotten about this attribute... Thanks
