### ISSUE TITLE
GetVehicleVelocity returns '0'

### ISSUE THREAD

**Issue by swedays** [ikkentim/SampSharp#246]
Hello. This function returns '0' in x,y,z. Why? What am I doing wrong?
`BaseVehicle.VehicleInternal.Instance.GetVehicleVelocity(PlayerInternal.Instance.GetPlayerVehicleID(player.Id), out x, out y, out z);`
For a pedestrian value is correct.
`PlayerInternal.Instance.GetPlayerVelocity(player.Id, out x, out y, out z);`

version 0.8.0-alpha1

**Comment by ikkentim** [comment]
I think output arguments were broken back in alpha1, we've had many alpha versions since.
