### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by EmanOK** [ikkentim/SampSharp#248]
Why doesn't the extension work?

```csharp
[assembly: SampSharpExtension(typeof(SampSharp.Example.ExampleExtension))]

namespace SampSharp.Example
{
    public class ExampleExtension : Extension
    {
        #region Overrides of Extension

        public override void PostLoad(BaseMode gameMode)
        {
            Console.WriteLine("ExampleExtension was loaded!");
        }

        #endregion
    }
}
```

**Comment by ikkentim** [comment]
- are you referencing this assembly/project from your gamemode?
- you might be getting hit by reference optimization. Make sure you reference at least one type or method from this assembly/project from your gamemode. A simple field ‘SomeTypeImExtrnsion foo;’ will do.

**Comment by EmanOK** [comment]
It works now. The problem was in the second item. 
I didn't even know what that could be, thanks for the quick answer.
