### ISSUE TITLE
problem with Alpha 0.8 and .Net Core 2.0

### ISSUE THREAD

**Issue by hottabych07** [ikkentim/SampSharp#250]
I know that in the Alpha version you need to create a console project and run samp-server.exe and this console project. But when I compiled the project, I got a .dll file, not a console .exe. in Debug mode, Visual Studio all starts fine. How can I get around this problem so that it compiles for me .exe? Or do I not need it and I make some mistake?

**Comment by ikkentim** [comment]
Read up on .net core applications and compilation.

See https://stackoverflow.com/questions/44074121/build-net-core-console-application-to-output-an-exe for example.
