### ISSUE TITLE
RegisterEvents and Controllers

### ISSUE THREAD

**Issue by hottabych07** [ikkentim/SampSharp#251]
Hi everyone, tell me please.

Here https://github.com/ikkentim/SampSharp/issues/224#issuecomment-345467091, ikkentim says that you can use [PooledType], I understand this thing replaces RegisterTypes, and the controller does not need to write at all? (Correct if I'm not right ).

And in general the question is, how should I use RegisterEvents? (create a controller, or there is another way, better)

**Comment by hottabych07** [comment]
heeeelp

**Comment by ikkentim** [comment]
[PooledType] allows you to specify a class should be used to create instances of a certain object type (player, vehicle, etc). For example, if you want to use a custom player class you can use `[PooledType] class Player : BasePlayer {}`

RegisterEvents is a controller thing which has nothing to do with the PooledType attribute. Simply create a controller to use this

**Comment by hottabych07** [comment]
Oh thank you, I understood everything, I still have the documentation to expand, it would be generally cool
