### ISSUE TITLE
Dialogs

### ISSUE THREAD

**Issue by hottabych07** [ikkentim/SampSharp#252]
How to use Dialogs(class) correctly?And how to interact with this?

**Comment by hottabych07** [comment]
Ok, how do I process it in DialogResponse?

**Comment by fvandillen** [comment]
You simply hook up the Response event of the dialog to a function or you process the response inline such as the following example: https://i.imgur.com/nJ2gk8A.png

**Comment by hottabych07** [comment]
thank you!
