### ISSUE TITLE
GameMode Builder (Missing)

### ISSUE THREAD

**Issue by Tagoff** [ikkentim/SampSharp#253]
I've created a Console Application to run a server with the GameModeBuilder but there isn't any class with this name in any assemblies ...

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using SampSharp.GameMode; // Contains BaseMode class
using SampSharp.GameMode.Controllers; // Contains ControllerCollection class

namespace GameServer
{
    class Program
    {
        static void Main(string[] args)
        {
            new GameModeBuilder()
            .UseLogLevel(CoreLogLevel.Debug)
            .UseStartBehaviour(GameModeStartBehaviour.FakeGmx)
            .Use<GameMode>()
            .Run();
        }
    }

    public class GameMode : BaseMode
    {
        #region Overrides of BaseMode

        protected override void OnInitialized(EventArgs e)
        {
            Console.WriteLine("\n----------------------------------");
            Console.WriteLine(" Blank Gamemode by your name here");
            Console.WriteLine("----------------------------------\n");

            base.OnInitialized(e);
        }

        protected override void LoadControllers(ControllerCollection controllers)
        {
            base.LoadControllers(controllers);
        }

        #endregion
    }
}
```

**Comment by ikkentim** [comment]
You must also add SampSharp.Core NuGet package as a reference to your project.

The SampSharp.GameMode package should itself have referenced the Core package, but it doesn't due to an outstanding bug.

**Comment by Tagoff** [comment]
I Added the Nuget Link --> http://nuget.timpotze.nl/api/v2/ and just there are "SampSharp.GameMode and SampSharp.Streamer". I didn't find the Core...

**Comment by ikkentim** [comment]
Make sure to tick the "include prereleases" checkbox

**Comment by Tagoff** [comment]
I did what you said, and there is a "SampSharp.GameMode" Version: 0.8.0-alpha6 ... is this? 

When i try to update it i get a error:

Can not resolve as dependencies. 'NETStandard.Library 1.6.0' is not compatible with 'SampSharp.Core 0.8.0-alpha6 restriction: NETStandard.Library (> = 1.6.1)'.

**Comment by ikkentim** [comment]
What .NET Core or .NET Framework version are you using? Try updating to a more recent version.

**Comment by Tagoff** [comment]
I update my visual studio and nothing. I'm using the 4.6.1 version of the .Net Framwork on the Console project to start the server.

**Comment by Tagoff** [comment]
I found it: https://www.nuget.org/packages/NETStandard.Library/2.0.3 

:)

**Comment by ikkentim** [comment]
try installing 4.7.2 https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers
