### ISSUE TITLE
PoolContainer for PlayerTextDraws: sometimes it can't keep up with the game

### ISSUE THREAD

**Issue by Xalphox** [ikkentim/SampSharp#257]
If I dispose a PlayerTextdraw and then create one very shortly after, I often get duplicate key conflicts despite the fact that the reality is the game still sees <256 textdraws. I've gotten around this temporarily by replacing Add with:

        public void Add(int key, TInstance item)
        {
            if (key == UnidentifiedId)
                _unidentifiedItems.Add(item);
            else
            {
                //if (_identifiedItems.ContainsKey(key)) throw new ArgumentException("duplicate key", nameof(key));

                //_identifiedItems.Add(key, item);
                _identifiedItems[key] = item;
            }
        }

**Comment by ikkentim** [comment]
That’s an odd one, will look into it tomorrow.

**Comment by ikkentim** [comment]
I've not been able to reproduce this; is this still an issue?

**Comment by ikkentim** [comment]
Let me know if this is still is an issue and you have some code to reproduce this issue.
