### ISSUE TITLE
DynamicPickupException 

### ISSUE THREAD

**Issue by Tagoff** [ikkentim/SampSharp#264]
```
protected override void OnInitialized(EventArgs e)
        {
            base.OnInitialized(e);

            new DynamicPickup(1274, 1, new Vector3(2530.4463, -2434.7368, 17.8828), 100F);
        }
```

Always when i call the DynamicPickup (streamer) throws a exception... what is going wrong?

**Comment by ikkentim** [comment]
What kind of exception? What is stacktrace?

**Comment by Tagoff** [comment]
It's throws 2 exceptions at once.

Exceção interna 1:
TypeInitializationException: The type initializer for 'SampSharp.Streamer.Streamer' threw an exception.

Exceção interna 2:
TypeLoadException: Could not load type SampSharp.GameMode.API.NativeObjects.NativeObjectProxyFactory from assembly SampSharp.GameMode, Version=0.8.0.0, Culture=neutral, PublicKeyToken=null.

**Comment by ikkentim** [comment]
What versions of SampSharp.Streamer and SampSharp.Core are you using? Try and make sure you're using the latest versions.
