### ISSUE TITLE
Can't use feature of BasePlayer subclass in Commands

### ISSUE THREAD

**Issue by Zelyutin** [ikkentim/SampSharp#267]
I'm trying to make a command from the example at wiki/documentation. My version is 0.7.6
```
using SampSharp.GameMode.World;
using SampSharp.GameMode.SAMP.Commands;
class Player : BasePlayer
    {
        [Command("h")]
        private bool HelloWorldCommand(int times)
        {
            for (var i = 0; i < times; i++)
                sender.SendClientMessage("Hello, world!");
            return true;
        }
    }
```
But I've got an error "The name 'sender' does not exist in the current context".
I've checked BasePlayer and some other command code to find sender but reached no result.

Realization with static compiles well.
Do I understand something wrong about how it should work?

**Comment by Zelyutin** [comment]
Oh, I've got it.
There should be `this` instead of `sender` as it seems. Replaced it and the command started working!

**Comment by moono-samp** [comment]
Man, do not specify `this`. After all, there are no ambiguities.

**Comment by Zelyutin** [comment]
Thanks!
Is there a difference, will I specify it or not?

**Comment by ikkentim** [comment]
No difference, just nicer code.

**Comment by Zelyutin** [comment]
Okay, thank you both!
I'm from PHP by the way, where `this` is needed to use another functions of current class exemplar. Because function without `this` would mean in this scope that it doesn't belong to some class. 

ikkentim, don't you mind that I had corrected this moment in wiki?

**Comment by ikkentim** [comment]
@Zelyutin No problem!

**Comment by SaSiNO97** [comment]
By the way, I want to say that I disagree with not using `this` when there is no ambiguity, it sometimes makes sense to use it anyways and makes the code more understandable.

**Comment by fvandillen** [comment]
This is a very old issue. If you have a new problem, feel free to submit a new issue.

FYI: Using this or not, is a code style preference which has absolutely no impact on the functionality or SampSharp.
