### ISSUE TITLE
Building 'Player/Vehicle Model/etc not found' behaviour in Commands 

### ISSUE THREAD

**Issue by Zelyutin** [ikkentim/SampSharp#268]
The problem is when using some built-in brilliant types in commands like BasePlayer or VehicleModelType it's not able to know whether entity is found by it's identifier or not. 
``` C#
[Command("send")]
private void SendCommand(BasePlayer friend, String message)
```
If someone type `/send Johny Hello` and player Johny is not on the server at the moment, sender will only get standart usage message and will think that he uses the command wrongly while everyting is right. That is not the preferable behaviour. 
Sending something like "Your friend is not online now" is not available because command processor doesn't invoke function in this situatuion.

**Comment by sionzeecz** [comment]
This could be fixed by adding something like [NullableParam] in front of parameter. To mark parameter to not return usage if it is incorrect. 

I will made a PR.

Example:

    [Command("send")]
    private void SendCommand([NullableParam] BasePlayer friend, String message)

    if(friend == null) throw new RuntimeException("You don't have friends.");

**Comment by ikkentim** [comment]
Decided to accept the PR. Added `[NullableParam]` to indicate a Player or Vehicle is allowed to be null. Using nullable enum values like `VehicleModelType?` enums can be marked as nullable.
