### ISSUE TITLE
Player does not spawn after gamemode restart when creating vehicle in OnInitialized callback

### ISSUE THREAD

**Issue by UareBugged** [ikkentim/SampSharp#271]
OnConnected callback is called but class select immediately disappears after showing and player is not being spawned. Both gamemode, samp-server and client have to be restarted.

**Comment by ikkentim** [comment]
This has been improved 9baece10c4b552fbf9e2ed17a43fbbd5f82b013a but a bug can still sometimes occur where the class selection will not appear. 

This seems is caused by some kind of SA-MP bug where filterscripts are not properly unloaded.

**Comment by ikkentim** [comment]
Should be fixed with 5c63c8985fb46bdbb04693dd808cb5a2e2fec798
