### ISSUE TITLE
Implicit command`s name

### ISSUE THREAD

**Issue by ghost** [ikkentim/SampSharp#273]
Very often I write so:
```csharp
[Command("help")]
public void HelpCommand() {}
```
It is noticeable that the name is duplicated. Therefore, it would be more convenient to write so:
```csharp
[Command]
public void HelpCommand() {}
```
That is, the name of the command should be the name of the method(with the removal of the word "Command", if it is at the end.)

**Comment by ikkentim** [comment]
Great idea!

**Comment by moono-samp** [comment]
I think for CommandGroup you can do the same.
```csharp
[CommandGroup]
static class AdminCommands
{
    [Command]
    public static void Kick(BasePlayer sender, BasePlayer taget) {}
    [Command]
    public static void Ban(BasePlayer sender, BasePlayer taget) {}
}
```
And since, the CommandGroup attribute implies that in the class except for the commands nothing will be:
```csharp
[CommandGroup]
static class AdminCommands
{
    public static void Kick(BasePlayer sender, BasePlayer taget) {}
    public static void Ban(BasePlayer sender, BasePlayer taget) {}
}
```
Although the latter is superfluous though.
