### ISSUE TITLE
VehicleModelType recognizing problem

### ISSUE THREAD

**Issue by Zelyutin** [ikkentim/SampSharp#274]
Writing 500 or 600 model types in the command leads to Usage message instead of proper command execution.
As it seems, It conflicts with NRG-500 and PCJ-600 names.
Interesting, that 400 model doesn't conflict with AT400 plane and works well.

**Comment by ikkentim** [comment]
Conflicting vehicle names:
- AT-400
- BF-400
- NRG-500
- PCJ-600

In case a valid number was entered, the vehicle model ID should be used, otherwise, the name should be used.
