### ISSUE TITLE
Crash on RCON gmx

### ISSUE THREAD

**Issue by boreek** [ikkentim/SampSharp#280]
server was crashed on try reload gamemode with `rcon gmx`

> SA-MP Server: 0.3.7-R2
> 
> Exception At Address: 0x0047E047 Module: (samp-server.exe)
> 
> Registers:
> EAX: 0x028000FE	EBX: 0x000000FE	ECX: 0x00000000	EDX: 0x00470000
> ESI: 0x02874B0C	EDI: 0x000F4726	EBP: 0x02870430	ESP: 0x0019F8DC
> EFLAGS: 0x00010212

**Comment by ikkentim** [comment]
This was with hosted mode enabled?

**Comment by ikkentim** [comment]
Have not been able to reproduce this, do you have any additional info?

**Comment by ikkentim** [comment]
Thanks for the info! This will help me track down the bug.

**Comment by sionzeecz** [comment]
The issue occurs when is called "set_on" in "intermission.cpp", I will post more info into this comment when I research something.

**Comment by htfranek** [comment]
I can indeed confirm this problem happens. Wierd that you weren't initially able to reproduce the issue as it always happens.

**Comment by ikkentim** [comment]
Ah thanks! Yes I actually had intermissions off. There are a number of issues with intermissions/hot swapping. I'll fix this crash at the very least

**Comment by ikkentim** [comment]
Disabled player pool destroy functions in the intermission. I want to improve sampsharp's cleanup in the future anyway, the intermission filterscript doesn't seem to be the right way anyway. Also, it's only used when not in hosted mode, and hosted mode is the advised way of running the server in production.
