### ISSUE TITLE
Cyrillic symbols in SAMP#

### ISSUE THREAD

**Issue by Kambet** [ikkentim/SampSharp#281]
Hi!

I tried to send a message with russian text for player and i can't solve one problem
sender.SendClientMessage("тест:"); only sends me "????:"

How can i fix this? I also tried to add different codepages to my server.cfg, but it doesnt helps

I am using last alpha SampSharp version

**Comment by DENLN** [comment]
[cp1251.txt](https://github.com/ikkentim/SampSharp/files/2497992/cp1251.txt)

**in Program.cs** 
```
new GameModeBuilder()
                .UseLogLevel(CoreLogLevel.Info)
                .UseStartBehaviour(GameModeStartBehaviour.FakeGmx)
                .UseExitBehaviour(GameModeExitBehaviour.Restart)
                .UseEncoding(Path.Combine(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location), "codepages\\cp1251.txt"))
                .Use<GameMode>()
                .Run();
```

**Comment by Kambet** [comment]
Will this work at Linux?
Windows problem solved.

**Comment by ikkentim** [comment]
Yes, this will also work on Linux.
