### ISSUE TITLE
Central European Characters [Windows-1250] (Č, č, Ď, ď, Ě, ě, Ň, ň, Ř, ř, Ť, ť, Ů, ů) not working

### ISSUE THREAD

**Issue by htfranek** [ikkentim/SampSharp#284]
Hello, so first of all let me say I love your work. Really great!

Now to the issue - I saw a similar problem was already discussed and supposedly resolved, YET these symbols I wrote in the issue topic still don't work. ([link to the mentioned topic](https://github.com/ikkentim/SampSharp/issues/9))

Do you think there is something that could be done about that? These are classic windows-1250 CE chars

EDIT: People from my country (Czech Republic) have to set the Windows language to Czech to see the symbols in SA-MP, when you will try to write them, you will probably see their counters (which are pure C, c, D, d and so on). Though when I add a text using SampSharp the symbols don't appear at all in the chat. There is just a blank space instead of them.

**Comment by htfranek** [comment]
closed because after further testing I didn't make them work using original Pawn code either. Probably the SAMP font doesn't support them.

**Comment by htfranek** [comment]
vbdfx

**Comment by ikkentim** [comment]
Have you set the codepage properly? Assuming you're using sampsharp 0.8-alpha (which you should!) you can use .SetEncoding in the game mode builder to set this up properly. 0.8 doesn't really have much documentation yet (sorry!), if you want to fire some questions at us to get you set up using sampsharp or specifically version 0.8, come join our SampSharp chat group on Slack! it will generally grant you much faster response times than github issues.

**Comment by htfranek** [comment]
I didn't want to use the alphas because of the lack of documentation, that's why I am writing the gamemode in the latest stable. If there is the possibility to discuss possible issues on the Slack maybe I'll rewrite it into the new version after all. Thanks, will try the setEncoding once I have it migrated.

**Comment by sionzeecz** [comment]
You should use encoding files inside `codeblocks` directory instead of Encoding.UTF8 etc...
For an example:
`UseEncoding(Path.Combine(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location), "path_to_root_dir\\codepages\\cp1251.txt"))`

**Comment by htfranek** [comment]
Great, that worked! Thanks!
