### ISSUE TITLE
These releases violate the specified licence agreement

### ISSUE THREAD

**Issue by BigETI** [ikkentim/SampSharp#285]
After researching the repositories https://github.com/rw-mp/modules-api and https://github.com/rw-mp/python-module I've encountered that these port some contents of https://github.com/ikkentim/SampSharp/tree/master/src/SampSharp.GameMode/Definitions into C++, without crediting your work, neither mentioning the original source code in any way.

https://github.com/ikkentim/SampSharp/blob/master/LICENSE#L89-L128

**Comment by ikkentim** [comment]
Hmm indeed, it even has the same typos. I’ll look into this, thanks

**Comment by 0x452** [comment]
Hi @ikkentim, sorry for using your definitions without license, we’ve changed them to ours, asap we will update it at python-module.
