### ISSUE TITLE
Disallow access to event invoker and add correct EventArgs implementation

### ISSUE THREAD

**Issue by sionzeecz** [ikkentim/SampSharp#286]
Hello, when developer inherits from BaseMode class there are also inherited invoke functions.

        /// <summary>
        ///     Raises the <see cref="PlayerConnected" /> event.
        /// </summary>
        /// <param name="player">The player triggering the event.</param>
        /// <param name="e">An <see cref="EventArgs" /> that contains the event data. </param>
        protected virtual void OnPlayerConnected(BasePlayer player, EventArgs e)
        {
            PlayerConnected?.Invoke(player, e);
        }

These methods should not be virtual and protected. I recommend to make them internal because they are not specified to be called or were override from developer.

Correct usage should be override onInitialize and register listeners for events like PlayerConnected.

### Issue 2# EventArgs

You are using first parameter ("sender") incorrect when invoking event. There should be reference to instance what invoked the actual "invoke" method but you are passing player instead of it.

        PlayerConnected?.Invoke(player, e);

The second parameter is "EventArgs" and it should be "PlayerEventArgs" or "ConnectEventArgs" to access the player from the event. There is more methods with same issue. Example:

        /// <summary>
        ///     Occurs when the <see cref="OnPlayerConnected" /> callback is being called.
        ///     This callback is called when a player connects to the server.
        /// </summary>
        public event EventHandler<EventArgs> PlayerConnected;

Don't take this issue offensive. This is just what I find out when using your API and this is not "standard".

**Comment by ikkentim** [comment]
on part 1 of this issue:
This is a normal pattern in c#. See [the c# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-raise-base-class-events-in-derived-classes) for an example and more info.

**Comment by ikkentim** [comment]
The 2nd part is a bit tough. I think I'll leave it as-is at least for 0.8, because changing this will be a majorly breaking change. I'll change it (merge PR) for 0.9.

**Comment by sionzeecz** [comment]
I agree with that this is normal pattern for an application but not for API based application.
This sounds incorrect to me because everyone will override the invoker method instead of using events.

**Comment by ikkentim** [comment]
This is totally fine, please are allowed to overwrite it and implement their own logic, perform actions before invoking the event, etc.

SampSharp is the API for an application layer, you can compare it to WinForms, where the same event pattern is used.

**Comment by ikkentim** [comment]
Closing in favor of SampSharp.Entities
