### ISSUE TITLE
Add properties for accessing paths

### ISSUE THREAD

**Issue by sionzeecz** [ikkentim/SampSharp#292]
By data management I mean a class where will be Paths to some directories. E.G.: (ServerRootDirectory, GameModeDataDirectory?)

Through Assembly you can access where is console application started but if you put your application to something like /home/deploy/gamemode and server to /home/servers/samp you have to write your own configuration for locating the server directory or hard-code write it into code. 

To me, the best way would be to add path to Server root directory.

Instead of calculating path you can then easily write Path.Combine(Assets.ServerRootDir, "Data")...

**Comment by ikkentim** [comment]
Good idea, will implement this soon.
