### ISSUE TITLE
SampSharp server hangs in shared mode after being idle for a while

### ISSUE THREAD

**Issue by ikkentim** [ikkentim/SampSharp#294]
> Rexmundier [3:27 PM]
Hi, is this happening to anyone too? When I leave the server idle for a while it is impossible to connect and I have to restart. There is some serious problem somewhere in the connection between the SampSharp server and the Samp Server...
Pasted image at 2018-11-26, 3:27 PM (Server console "Kicking X because they didn't logon to the game.")
>
> Pasted image at 2018-11-26, 3:27 PM (Game "Server closed the connection.")
>
> Can't connect at all, no matter what I do. Until the server is restarted. Then it works (for some time until it doesn't).
>
> ikkentim [3:29 PM]
What’s in the sampsharp server console?
>
> Rexmundier [3:34 PM]
nope, nothing, the server is like it is running
No errors anywhere in the console except that the player is kicked
but no player can join, they just get kicked at every attempt
>
> ikkentim [3:36 PM]
please note that in production you're better of running in hosted mode (see pinned message in this channel). But this is definitely not right. You haven't accidentally selected text in either server console? That freezes the server. Has this happened before?
>
> Rexmundier [3:39 PM]
No, I know that console can be frozen by selecting text (I even disabled the selection in it, so it's not possible to do it), but that didn't happen. It's like 5x a day I get notified that it's impossible to join. Then I have to go and restart it.
But it is in the production where it bothers me, so I will have a look at that pinned message you speak of (edited)

**Comment by sionzeecz** [comment]
I will be glad if you can answer these questions.

Is the production build a real "release" build? 
I mean if is not built it as "debug".

Is this happening to debug version too?
Is this happening to production environment only?
Do you have or can you enable Debug level?
(it is in the GameModeBuilder)

Maybe there could be debug about connection when something went wrong.

**Comment by ikkentim** [comment]
Debug logging is not available in a release build.

**Comment by htfranek** [comment]
> I will be glad if you can answer these questions.
> 
> Is the production build a real "release" build?
> I mean if is not built it as "debug".
> 
> Is this happening to debug version too?
> Is this happening to production environment only?
> Do you have or can you enable Debug level?
> (it is in the GameModeBuilder)
> 
> Maybe there could be debug about connection when something went wrong.

Sure thing --

Its a release build.

Happend once in the Debug, but I didn't really care about that, I usually just turn debug on for testing something new I added, it isn't like I keep it running unattended as do I the Production release.

Don't have the debug level enabled. Ikketim just commented that the debug logging is not available in a release build, so it wouldn't do much good.

**Comment by sionzeecz** [comment]
"Happend once in the Debug", it is mean it is not just happening to release build.
That is good to know. Thank you.

**Comment by ikkentim** [comment]
Anyone got new info on this? I have not been able to reproduce this. If someone has a repro case I'll reopen this.

As far as I can see this does not happen in hosted mode.
