### ISSUE TITLE
Server doesnt load

### ISSUE THREAD

**Issue by joaoseidel** [ikkentim/SampSharp#297]
I'm getting this (screenshot below) when I try to start the server, I'm not getting the OnInitialized event 

https://prnt.sc/lsgizi

**Comment by ikkentim** [comment]
Are you starting both the server and the game mode (.net) or are you running in hosted mode?

**Comment by joaoseidel** [comment]
I'm starting both servers, but when I run my console app it doesnt return nothing, just a blank terminal, is this right?

**Comment by ikkentim** [comment]
Sorry for the delay; What does your Program.cs (application entry point) look like?
