### ISSUE TITLE
Response for Dialogs

### ISSUE THREAD

**Issue by chyakka** [ikkentim/SampSharp#301]
While the dialog response event looks out for enter, esc or double clicking a list item I can't check which one they did, so if I wanted to use escape to close a dialog I can't seem to find a way to go about it.

The event args didn't seem to have any option about how the response was handled.

Is being able to identify how they triggered the response event a possibility or is it already there and I'm just missing something?

**Comment by ikkentim** [comment]
This is not possible, because SA-MP does not provide this information: see http://wiki.sa-mp.com/wiki/OnDialogResponse

**Comment by chyakka** [comment]
When using PAWN I believe pressing escape returns 0 on response. While getting specific triggers for the event may not be possible is getting escape to just trigger the right button a possibility?

**Comment by ikkentim** [comment]
In SA-MP it will indeed cause "response" to be 0 which represents the right button. Maybe I should add a bit of documentation to it...
