### ISSUE TITLE
Suggestion: get all elements for owner in IdentifiedOwnedPool

### ISSUE THREAD

**Issue by Zelyutin** [ikkentim/SampSharp#307]
Hi!

Now it's possible to use PlayerObject.All to get all the player's object, but it's necessary to check after, who is the owner of the current object.

I think it would be great to have ability in the IdentifiedOwnedPool to get All elements for one Owner. Like .AllBy(Owner) or .OwnedBy(Owner) or AllOwnedBy(Owner) or something like that.

**Comment by iRealWorlds** [comment]
Isn't this achieved by the `Of(TOwner owner)` method in the `IdentifiedOwnedPool`?

**Comment by ikkentim** [comment]
Indeed!

**Comment by Zelyutin** [comment]
@iRealWorlds , Thank you!
