### ISSUE TITLE
Failed to retrieve info from nuget repo

### ISSUE THREAD

**Issue by MichaelBelgium** [ikkentim/SampSharp#314]
Wanna try this stuff out but:

`Error occurred while restoring NuGet packages: Failed to retrieve information about 'SampSharp.RakNet' from remote source 'http://nuget.timpotze.nl/api/v2/FindPackagesById()?id='SampSharp.RakNet'&semVerLevel=2.0.0'.`

Also what kind of project type does it need to be when creating a new server/project? A class library or an empty project? Or anything else?

**Comment by ikkentim** [comment]
I’ll take a look at the error

You need a console application

**Comment by MichaelBelgium** [comment]
Maybe this helps more, something with the host or so:

```
[SampSharp] The V2 feed at 'http://nuget.timpotze.nl/api/v2/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='net472'&includePrerelease=false&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '502 Bad Gateway'.
[SampSharp] The V2 feed at 'http://nuget.timpotze.nl/api/v2/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='net472'&includePrerelease=false&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '502 Bad Gateway'.
```

Occurs when browsing for nuget packages on the SampSharp package source

**Comment by ikkentim** [comment]
php-fpm is refusing to do anything at the moment - investigating

**Comment by ikkentim** [comment]
It was an issue with one of my other websites which are timing out during external requests

**Comment by ikkentim** [comment]
Could you verify it is working now?

**Comment by MichaelBelgium** [comment]
> Could you verify it is working now?

Yes it does! Thank you
