### ISSUE TITLE
Creating text and keys pressing analog for Dialog.ShowAsync()

### ISSUE THREAD

**Issue by Zelyutin** [ikkentim/SampSharp#316]
Is it able to create Dialog.ShowAsync() analog for player text typing and keys pressing?
If we say "Press jump button", and waiting for this in the function.

**Comment by ikkentim** [comment]
For dialogs you already have the `ShowAsync` method. By `text`, what do you mean? input text?

**Comment by Zelyutin** [comment]
Input text, yes. Or maybe command text also.
Something like "Write /somecommand [param1] [param2] right now." And you want to wait for it with await/async.

**Comment by ikkentim** [comment]
Decided not to provide this from within the framework, needs a user solution.
