### ISSUE TITLE
SampSharp freeze when accessing vehicle properties in vehicle.Spawn event

### ISSUE THREAD

**Issue by jstylezzz** [ikkentim/SampSharp#318]
I stumbled upon an issue that causes the entire SampSharp instance to lock up. Looks like anytime I access or modify a BaseVehicle's properties in the `OnSpawn` method override or `Spawn` event this lock up happens. Below is the most bare-bones example I could produce.

```
using SampSharp.Core;
using SampSharp.GameMode;
using SampSharp.GameMode.Definitions;
using SampSharp.GameMode.World;
using System;

namespace VTest
{
    class Program
    {
        static void Main(string[] args)
        {
            new GameModeBuilder().Use<MyGameMode>().Run();
        }
    }

    public class MyGameMode : BaseMode
    {
        protected override void OnInitialized(EventArgs e)
        {
            base.OnInitialized(e);
            BaseVehicle vehicle = BaseVehicle.Create(VehicleModelType.Taxi, Vector3.Zero, 0, 1, 1);
            vehicle.Spawn += OnTestVehicleSpawn;
            vehicle.Respawn();

            Console.WriteLine("DONE INIT");
        }

        protected override void OnVehicleSpawned(BaseVehicle vehicle, EventArgs e)
        {
            base.OnVehicleSpawned(vehicle, e);
            Console.WriteLine($"GAMEMODE EVENT ONVEHICLESPAWNED {vehicle.ModelInfo.Name}");
        }

        private void OnTestVehicleSpawn(object sender, EventArgs e)
        {
            Console.WriteLine($"VEHICLE INSTANCE EVENT ONVEHICLESPAWNED {(sender as BaseVehicle).ModelInfo.Name}");
        }
    }
}
```

I tried running the above example using v0.8.0 SampSharp NuGet packages and plugin binaries from the release page (release tagged 0.8.0), it won't ever get to print the `DONE INIT` message. 
It doesn't throw any exceptions or give any messages when this happens either, so I'm kinda lost on how to deal with this.

Not sure if this is related, but it looks like the overridden `OnSpawn`  method in a custom vehicle class or in the game mode class is not called at all without using `vehicleinstance.Respawn()`. This can be tested in the above example as well, if you comment out `vehicle.Respawn()`, the `GAMEMODE EVENT ONVEHICLESPAWNED` line does not appear.

Thanks for your time, if there's any more info I can provide please let me know and I'll get on it.

**Comment by ikkentim** [comment]
Thanks for the repro case, I’ll look into it this week

**Comment by ikkentim** [comment]
This is not a problem in hosted mode but is a problem in shared (separated processes) mode. As a workaround you can use hosted mode. (Running .net core inside of samp-server.exe)

add `gamemode path/to/your/gamemode.dll` to your server config and see https://sampsharp.net/setup#dotnet-runtime .

I'll try to fix this issue in the meantime.

**Comment by ikkentim** [comment]
I've identified and fixed the problem. Here's a new build of the plugin. Could you replace the plugin in the plugins folder of your server and confirm the issue is fixed?
[SampSharp.zip](https://github.com/ikkentim/SampSharp/files/3298201/SampSharp.zip)

**Comment by jstylezzz** [comment]
> 
> 
> I've identified and fixed the problem. Here's a new build of the plugin. Could you replace the plugin in the plugins folder of your server and confirm the issue is fixed?
> [SampSharp.zip](https://github.com/ikkentim/SampSharp/files/3298201/SampSharp.zip)

My mode seems to starts up and run fine with the file from the archive. Thanks a lot for your time and efforts, I love this framework!
