### ISSUE TITLE
GetAnimationName doesn't return animation name but returns lib

### ISSUE THREAD

**Issue by Sonic512** [ikkentim/SampSharp#323]
![2019 10 07-17 57](https://user-images.githubusercontent.com/56268694/66329442-d1415d00-e92e-11e9-828d-cb0c29166dc8.png)
When being alone on server and getting my animation^
When player joined, a name stored his part of nickname counting from end.
For example, player name is: Frenando_Graciaz
, name stores: ando_Graciaz.

![yes](https://user-images.githubusercontent.com/56268694/66329632-1ebdca00-e92f-11e9-9501-b303b40781f9.PNG)

**Comment by ikkentim** [comment]
@Sonic512 It's been a while since I last tried to reproduce this, do you know what animation you had applied to the player?

**Comment by Sonic512** [comment]
Nope, but it doesn't matter in this case.

**Comment by ikkentim** [comment]
I think I have fixed this in the next release.

I think the player returned an invalid animation index (probably 0), which would return a corrupt string in GetAnimationName.

I've fixed natives returning corrupt strings in f8033a9
