### ISSUE TITLE
Missing AllowInteriorWeapons on SampSharp.Entities

### ISSUE THREAD

**Issue by Eidorian** [ikkentim/SampSharp#332]
Missing `AllowInteriorWeapons(bool allow)` on **SampSharp.Entities** (`IServerService`)

**Comment by ikkentim** [comment]
@Eidorian is this necessary? According to the wiki it doesn't work anymore

https://wiki.sa-mp.com/wiki/AllowInteriorWeapons :

> **Warning** This function does not work in the current SA:MP version!

**Comment by Eidorian** [comment]
Oh! Just used by default in previous version of my GM without paying attention :rofl: 

Sorry, can be closed.
