### ISSUE TITLE
SampSharp IN Windows Form

### ISSUE THREAD

**Issue by amirhoseinadlfar** [ikkentim/SampSharp#335]
I Try Run SampSharp in Windows Form
But When I Click Start Button The App Has Been Lock And I Cant Do Any Work
https://photos.app.goo.gl/yw8foiJsvNk5CPqB6
How Can Help Me?
My Code

using System;
using System.Windows.Forms;
using SampSharp.Core;
using SampSharp.GameMode.Events;
using SampSharp.GameMode.World;

namespace TestSampWindowsForm
{
    public partial class Form1 : Form
    {
        GameModeBuilder game = new GameModeBuilder();
        public Form1()
        {
            InitializeComponent();
            GameMode.Form = this;
            game.Use<GameMode>();
        }

        private void Button1_Click(object sender, EventArgs e)
        {
            game.Run();
            button2.Enabled = !(button1.Enabled = false);
        }

        private void Button2_Click(object sender, EventArgs e)
        {
            game.Use(null);
            button1.Enabled = !(button2.Enabled = false);
        }
    }
    public class GameMode:SampSharp.GameMode.BaseMode
    {
        public static Form1 Form = null;
        protected override void OnPlayerConnected(BasePlayer player, EventArgs e)
        {
            base.OnPlayerConnected(player, e);
            player.SendClientMessage($"Wellcome {player.Name} This is Just For Test");
            Form.listBox1.Items.Add(player.Name);
        }
        protected override void OnPlayerDisconnected(BasePlayer player, DisconnectEventArgs e)
        {
            base.OnPlayerDisconnected(player, e);
            Form.listBox1.Items.Remove(player.Name);
        }
    }
}

**Comment by amirhoseinadlfar** [comment]
[https://lh3.googleusercontent.com/ypzgQl3ExYoDsf7c8uzu2eIEO1c0rFZBDiUWQmmVOlhmXx6RCkvVBSUytpCvyTwnObC7cFPSFleP2a9d3hqQGLCvn155c7Ro7k10YLneBT2BzyF6bHWvxFjkPdk9U0V85diTLdpF0Adg-Ziy2P5SKjjT_Rt5HGUr5oKwEM_aGWNaOJwM5vQlWU5mVBMvMuButnlUo9ti_r387Er1onmurHkQcxlvjsFdIKH9rQYMmO4PWUQBy1kKifJlM3GAfZ31BeTaaB2QmretMjTFBwr4vtLI6e458d437FLLQb5RcjV8gf6Xf6f7PzzfAJxQNbx-n1SjR6WpAPahrMYPjH8_Dx0hV7IVS_scH-FfVR38xa-FboESTRlMj3vIbZvsYQVP7dqQ4-C18Y4VJoe87TNLujnvVjLVKGPOjokYhspZnKLe4yfv9HsOXMPx84lzdjfg2nm0ZWsbStw4kcP8clxQdetyYMqOakTa2Bjfn2A-hWzObkK-1tbRRJ36UQlUB20XL9R_kJ5C6Ch5yWV4B1KF8u26KosjahtRNJPm9_kx1lU1XO628xD0r2ibKVo--Et3pMby8ABeDyxPdPSbPhnfr1juJL1NsbQylHNuBhXRhqxKeQ0KCfv2WvPGDflrqPCdPGvTkC2mHsVVEeyqgIU9YwC9ZTk1_Ldbr2TuwifuLY0PCA7pA2jxIbE=w1112-h625-no](url)

**Comment by amirhoseinadlfar** [comment]
https://photos.app.goo.gl/tgEYib12BRZaX7549

**Comment by amirhoseinadlfar** [comment]
I Run The Server Before Click Run And This GameMode Run By Pipe

**Comment by ikkentim** [comment]
SampSharp and Winforms both require full control over the main thread. You can't run both in one process. you're better off creating separate processes and having them communicate through a pipe or tcp or something.

**Comment by amirhoseinadlfar** [comment]
I tried 
`new Task(new Action(gamemode.Run));`
and
`new Thread(new ThreadStart(gamemode.Run))`
But not worked and server did not run gamemode

**Comment by ikkentim** [comment]
They need not just any thread, they need the MAIN thread. Just starting another thread won’t work. You need separate processes.

**Comment by amirhoseinadlfar** [comment]
can you give me an example ?

**Comment by ikkentim** [comment]
Simply have separate applications.

- Create one project which contains/runs the sampsharp gamemode
- Create another which contains/runs the winforms app
- Then later tackle the interprocess communication

I don't understand why you'd want a GUI by the way. But that's a decision of yours.
