### ISSUE TITLE
Samp 3.7.8 or 0.3.DL

### ISSUE THREAD

**Issue by amirhoseinadlfar** [ikkentim/SampSharp#336]
Can i use samp 0.3.DL Abilitys in sampsharp?

https://forum.sa-mp.com/showthread.php?t=647966

**Comment by Banditul** [comment]
You certanly can. But you will have to make the 0.3.7dl interface yourself(like the native function calls)

**Comment by amirhoseinadlfar** [comment]
yes but that will not Harmonious with SampSharp

**Comment by Eidorian** [comment]
Like Banditul said, 0.3DL works with S#. But you have to implement yourself new natives and callbacks from 0.3DL.

**Comment by Sonic512** [comment]
Check out our Slack, we will help you there
