### ISSUE TITLE
Suggestion for .GameMode.Display.TextDraw

### ISSUE THREAD

**Issue by Adrian4** [ikkentim/SampSharp#339]
Delete or make it optional UpdateClients(); in .GameMode.Display.TextDraw, doing this allows you to better use the global text drawing and show changes only when using Show()

**Comment by fvandillen** [comment]
What exactly are you suggesting? The update logic is already fully optional AFAIK.

**Comment by Adrian4** [comment]
@fvandillen I suggest that the GlobalTextdra not be updated until using .Show, as it would normally work in pawn, this would provide better control of the textdraws.

**Comment by ikkentim** [comment]
This would be a major breaking change, won't be changing this anymore in .GameMode. .Entities already works as you expect.
