### ISSUE TITLE
TextDraw

### ISSUE THREAD

**Issue by ArturSkot** [ikkentim/SampSharp#340]
Not displayed TextDraw fulebox
![15856725034711266830433186510601](https://user-images.githubusercontent.com/27450548/78051718-c409a600-7386-11ea-9028-ed58b1597415.jpg)
 as it should, only text!
Tell me how to fix it?

**Comment by ArturSkot** [comment]
![15856733761624186662663560549803](https://user-images.githubusercontent.com/27450548/78053104-cb31b380-7388-11ea-89be-72d219eb3832.jpg)

![15856738840044942370722586900063](https://user-images.githubusercontent.com/27450548/78053931-f7016900-7389-11ea-943c-64ab77642d5b.jpg)

**Comment by ikkentim** [comment]
please copy and paste the code instead of taking a picture. it is unreadable.

**Comment by ArturSkot** [comment]
> please copy and paste the code instead of taking a picture. it is unreadable.

`using SampSharp.GameMode;
using SampSharp.GameMode.Definitions;
using SampSharp.GameMode.Display;
using SampSharp.GameMode.SAMP;
using SampSharp.GameMode.World;
using System;
using System.Collections.Generic;
using System.Text;

namespace RolePlayMode.TextDraws
{
    public class SpeedMeter
    {
        protected static TextDraw fulebox = new TextDraw(new Vector2(565.0f, 397.5f), "fulebox", TextDrawFont.Diploma, 0);
        protected static TextDraw fule = new TextDraw(new Vector2(475.5f, 392.5f), "Fule:", TextDrawFont.Normal, -1);

        protected static TextDraw speedbox = new TextDraw(new Vector2(630.0f, 410.0f), "speedbox", TextDrawFont.Diploma, 0);
        protected static TextDraw Speed = new TextDraw(new Vector2(475.0f, 407.000030f), "Speed:", TextDrawFont.Normal, -1);
        protected static TextDraw KM = new TextDraw(new Vector2(580.0f, 407.0f), "km/h", TextDrawFont.Normal, -1);

        SpeedMeter()        
        {
            fulebox.LetterSize = new Vector2(0.0f, 0.903334f);
            fulebox.Height = 470.0f;
            fulebox.Width = 0.0f;
            fulebox.Alignment = TextDrawAlignment.Left;
            fulebox.UseBox = true;
            fulebox.BackColor = 51;
            fulebox.BoxColor = 102;

            fule.LetterSize = new Vector2(0.449999f, 1.6f);
            fule.Alignment = TextDrawAlignment.Left;
            fule.UseBox = true;
            fule.BoxColor = 0;
            fule.Shadow = 0;
            fule.Outline = 1;
            fule.BackColor = 51;
            fule.Proportional = true;

            speedbox.LetterSize = new Vector2(0.0f, 2.5f);
            speedbox.Height = 470.0f;
            speedbox.Width = 0.0f;
            speedbox.Alignment = TextDrawAlignment.Left;
            speedbox.UseBox = true;
            speedbox.BackColor = 51;
            speedbox.BoxColor = 102;

            Speed.LetterSize = new Vector2(0.449999f, 1.6f);
            Speed.Height = 9.50f;
            Speed.Width = -92.400032f;
            Speed.Alignment = TextDrawAlignment.Left;
            Speed.BoxColor = 0;
            Speed.Shadow = 0;
            Speed.Outline = 1;
            Speed.BackColor = 51;
            Speed.Proportional = true;

            KM.LetterSize = new Vector2(0.449999, 1.616798f);
            KM.Height = -200.5f;
            KM.Width = -99.119995f;
            KM.Alignment = TextDrawAlignment.Left;
            KM.UseBox = true;
            KM.BoxColor = 0;
            KM.Shadow = 0;
            KM.Outline = 1;
            KM.BackColor = 51;
            KM.Proportional = true;
        }

        public static void Show(BasePlayer player) 
        {
            PlayerTextDraw speeddraw = new PlayerTextDraw(player, new Vector2(525.500000f, 392.500000f), "---");
            speeddraw.LetterSize = new Vector2(0.449999f, 1.6f);
            speeddraw.Alignment = TextDrawAlignment.Left;
            speeddraw.ForeColor = -1;
            speeddraw.UseBox = true;
            speeddraw.BoxColor = 0;
            speeddraw.Shadow = 0;
            speeddraw.Outline = 1;
            speeddraw.BackColor = 51;
            speeddraw.Font = TextDrawFont.Slim;
            speeddraw.Proportional = true;

            speeddraw.Show();


            fulebox.Show(player);
            speedbox.Show(player);
            fule.Show(player);
            Speed.Show(player);
            KM.Show(player);
        }
    }
}
`

**Comment by ArturSkot** [comment]
`
using SampSharp.GameMode;
using SampSharp.GameMode.Definitions;
using SampSharp.GameMode.Display;
using SampSharp.GameMode.SAMP;
using SampSharp.GameMode.World;
using System;
using System.Collections.Generic;
using System.Text;

namespace RolePlayMode.TextDraws
{
    public class SpeedMeter
    {
        protected static TextDraw fulebox = new TextDraw(new Vector2(565.0f, 397.5f), "fulebox", TextDrawFont.Diploma, 0);
        protected static TextDraw fule = new TextDraw(new Vector2(475.5f, 392.5f), "Fule:", TextDrawFont.Normal, -1);

        protected static TextDraw speedbox = new TextDraw(new Vector2(630.0f, 410.0f), "speedbox", TextDrawFont.Diploma, 0);
        protected static TextDraw Speed = new TextDraw(new Vector2(475.0f, 407.000030f), "Speed:", TextDrawFont.Normal, -1);
        protected static TextDraw KM = new TextDraw(new Vector2(580.0f, 407.0f), "km/h", TextDrawFont.Normal, -1);

        SpeedMeter()        
        {
            fulebox.LetterSize = new Vector2(0.0f, 0.903334f);
            fulebox.Height = 470.0f;
            fulebox.Width = 0.0f;
            fulebox.Alignment = TextDrawAlignment.Left;
            fulebox.UseBox = true;
            fulebox.BackColor = 51;
            fulebox.BoxColor = 102;

            fule.LetterSize = new Vector2(0.449999f, 1.6f);
            fule.Alignment = TextDrawAlignment.Left;
            fule.UseBox = true;
            fule.BoxColor = 0;
            fule.Shadow = 0;
            fule.Outline = 1;
            fule.BackColor = 51;
            fule.Proportional = true;

            speedbox.LetterSize = new Vector2(0.0f, 2.5f);
            speedbox.Height = 470.0f;
            speedbox.Width = 0.0f;
            speedbox.Alignment = TextDrawAlignment.Left;
            speedbox.UseBox = true;
            speedbox.BackColor = 51;
            speedbox.BoxColor = 102;

            Speed.LetterSize = new Vector2(0.449999f, 1.6f);
            Speed.Height = 9.50f;
            Speed.Width = -92.400032f;
            Speed.Alignment = TextDrawAlignment.Left;
            Speed.BoxColor = 0;
            Speed.Shadow = 0;
            Speed.Outline = 1;
            Speed.BackColor = 51;
            Speed.Proportional = true;

            KM.LetterSize = new Vector2(0.449999, 1.616798f);
            KM.Height = -200.5f;
            KM.Width = -99.119995f;
            KM.Alignment = TextDrawAlignment.Left;
            KM.UseBox = true;
            KM.BoxColor = 0;
            KM.Shadow = 0;
            KM.Outline = 1;
            KM.BackColor = 51;
            KM.Proportional = true;
        }

        public static void Show(BasePlayer player) 
        {
            PlayerTextDraw speeddraw = new PlayerTextDraw(player, new Vector2(525.500000f, 392.500000f), "---");
            speeddraw.LetterSize = new Vector2(0.449999f, 1.6f);
            speeddraw.Alignment = TextDrawAlignment.Left;
            speeddraw.ForeColor = -1;
            speeddraw.UseBox = true;
            speeddraw.BoxColor = 0;
            speeddraw.Shadow = 0;
            speeddraw.Outline = 1;
            speeddraw.BackColor = 51;
            speeddraw.Font = TextDrawFont.Slim;
            speeddraw.Proportional = true;

            speeddraw.Show();


            fulebox.Show(player);
            speedbox.Show(player);
            fule.Show(player);
            Speed.Show(player);
            KM.Show(player);
        }
    }
}
`

**Comment by ArturSkot** [comment]
using SampSharp.GameMode;
using SampSharp.GameMode.Definitions;
using SampSharp.GameMode.Display;
using SampSharp.GameMode.SAMP;
using SampSharp.GameMode.World;
using System;
using System.Collections.Generic;
using System.Text;

namespace RolePlayMode.TextDraws
{
public class SpeedMeter
{
protected static TextDraw fulebox = new TextDraw(new Vector2(565.0f, 397.5f), "fulebox", TextDrawFont.Diploma, 0);
protected static TextDraw fule = new TextDraw(new Vector2(475.5f, 392.5f), "Fule:", TextDrawFont.Normal, -1);

    protected static TextDraw speedbox = new TextDraw(new Vector2(630.0f, 410.0f), "speedbox", TextDrawFont.Diploma, 0);
    protected static TextDraw Speed = new TextDraw(new Vector2(475.0f, 407.000030f), "Speed:", TextDrawFont.Normal, -1);
    protected static TextDraw KM = new TextDraw(new Vector2(580.0f, 407.0f), "km/h", TextDrawFont.Normal, -1);

    SpeedMeter()        
    {
        fulebox.LetterSize = new Vector2(0.0f, 0.903334f);
        fulebox.Height = 470.0f;
        fulebox.Width = 0.0f;
        fulebox.Alignment = TextDrawAlignment.Left;
        fulebox.UseBox = true;
        fulebox.BackColor = 51;
        fulebox.BoxColor = 102;

        fule.LetterSize = new Vector2(0.449999f, 1.6f);
        fule.Alignment = TextDrawAlignment.Left;
        fule.UseBox = true;
        fule.BoxColor = 0;
        fule.Shadow = 0;
        fule.Outline = 1;
        fule.BackColor = 51;
        fule.Proportional = true;

        speedbox.LetterSize = new Vector2(0.0f, 2.5f);
        speedbox.Height = 470.0f;
        speedbox.Width = 0.0f;
        speedbox.Alignment = TextDrawAlignment.Left;
        speedbox.UseBox = true;
        speedbox.BackColor = 51;
        speedbox.BoxColor = 102;

        Speed.LetterSize = new Vector2(0.449999f, 1.6f);
        Speed.Height = 9.50f;
        Speed.Width = -92.400032f;
        Speed.Alignment = TextDrawAlignment.Left;
        Speed.BoxColor = 0;
        Speed.Shadow = 0;
        Speed.Outline = 1;
        Speed.BackColor = 51;
        Speed.Proportional = true;

        KM.LetterSize = new Vector2(0.449999, 1.616798f);
        KM.Height = -200.5f;
        KM.Width = -99.119995f;
        KM.Alignment = TextDrawAlignment.Left;
        KM.UseBox = true;
        KM.BoxColor = 0;
        KM.Shadow = 0;
        KM.Outline = 1;
        KM.BackColor = 51;
        KM.Proportional = true;
    }

    public static void Show(BasePlayer player) 
    {
        PlayerTextDraw speeddraw = new PlayerTextDraw(player, new Vector2(525.500000f, 392.500000f), "---");
        speeddraw.LetterSize = new Vector2(0.449999f, 1.6f);
        speeddraw.Alignment = TextDrawAlignment.Left;
        speeddraw.ForeColor = -1;
        speeddraw.UseBox = true;
        speeddraw.BoxColor = 0;
        speeddraw.Shadow = 0;
        speeddraw.Outline = 1;
        speeddraw.BackColor = 51;
        speeddraw.Font = TextDrawFont.Slim;
        speeddraw.Proportional = true;

        speeddraw.Show();


        fulebox.Show(player);
        speedbox.Show(player);
        fule.Show(player);
        Speed.Show(player);
        KM.Show(player);
    }
}
}

**Comment by Hy4e** [comment]
You haven't called "SpeedMeter" function which initializes textdraw fields.

**Comment by ArturSkot** [comment]
> You haven't called "SpeedMeter" function which initializes textdraw fields.

tell me how to do it?

**Comment by Hy4e** [comment]
new SpeedMeter();

**Comment by ArturSkot** [comment]
> new SpeedMeter();

sorry you misunderstood, there are no problems in initializing! draw attention to the textdraw photo in c # is displayed differently than in pawn!

**Comment by ArturSkot** [comment]
now everything works correctly thanks
