### ISSUE TITLE
BaseVehicle.Create ALWAYS returns instance NULL

### ISSUE THREAD

**Issue by Hy4e** [ikkentim/SampSharp#345]
As in title:
![](https://i.imgur.com/v8XIrVn.png)

**Comment by LDami** [comment]
Tried this:
```
BaseVehicle vehicle = BaseVehicle.Create(SampSharp.GameMode.Definitions.VehicleModelType.AT400, new SampSharp.GameMode.Vector3(1431.6393f, 1519.5398f, 10.5988f), 0.0f, 1, 1);
vehicle.LinkToInterior(1);
```

And it works fine for me. Check if BaseVehicle comes from SampSharp.GameMode.World.BaseVehicle;

**Comment by Hy4e** [comment]
Still happens.
![](https://i.imgur.com/dpr9rg1.png)

**Comment by ikkentim** [comment]
BaseVehicle.Create directly returns the value from IVehicleFactory, which is by default implemented by https://github.com/ikkentim/SampSharp/blob/master/src/SampSharp.GameMode/Factories/BaseVehicleFactory.cs . Unless the vehicle can't be created by samp (which is unlikely) you must be having a custom implementation of IVehicleFactory loaded.
