### ISSUE TITLE
ConnectNPC return a non-NPC BasePlayer

### ISSUE THREAD

**Issue by LDami** [ikkentim/SampSharp#346]
Hi !

When I connect a NPC to my server, the method returns a BasePlayer object containing property "IsNPC" to false:

```
BasePlayer bot = SampSharp.GameMode.SAMP.Server.ConnectNPC("testman", "npctest2");
bot.SetSpawnInfo(0, 0, new SampSharp.GameMode.Vector3(1431.6393f, 1519.5398f, 10.5988f), 0.0f);
bot.Spawn();
player.SendClientMessage("bot id = " + bot.Id); // bot.Id = 49 (50 slots server)
player.SendClientMessage("bot is npc = " + bot.IsNPC.ToString()); // bot.IsNPC = False
```

The file "npctest2".amx exists but the NPC does not appear.
Even so there is the line "[npc:join] testman has joined the server (1:127.0.0.1)" in SAMP server console.

Furthermore, is it possible to return null on "ConnectNPC" instead of BasePlayer.FindOrCreate(id) if the NPC was not correctly connected ?

**Comment by ikkentim** [comment]
I'll see if I can improve this, ConnectNPC does not report success or failsure, so I'll have to detect it myself somehow

**Comment by LDami** [comment]
Ok so there is no way for the moment to know why the NPC does not appear ?

**Comment by SaSiNO97** [comment]
I confirm `IsNPC` is returning `false`, even with NPCs created with the FCNPC plugin.
