### ISSUE TITLE
Unable to spawn after server restart

### ISSUE THREAD

**Issue by LDami** [ikkentim/SampSharp#347]
Hi,

If there is any clients connected to the server (player or NPC), the restart of the SampSharp executable (i keep the SAMP server oppened) provoke a bug.
At the restart of SampSharp executable, players are unable to spawn. Sometimes they spawn at the position 0.0, 0.0, 0.0.

How can we fix that ?

Thanks !

**Comment by ikkentim** [comment]
do you load any filterscripts from your server.cfg?

**Comment by LDami** [comment]
> do you load any filterscripts from your server.cfg? which ones?

Thanks for reply, I don't have any filterscripts or plugins loaded.

**Comment by ikkentim** [comment]
Could you share your SAMP server log?

**Comment by LDami** [comment]
[server_log.txt](https://github.com/ikkentim/SampSharp/files/4551556/server_log.txt)
[chatlog.txt](https://github.com/ikkentim/SampSharp/files/4551559/chatlog.txt)



This time, at the restart of the SampSharp .exe, I was able to spawn but at position 0.0 of the map.

**Comment by ikkentim** [comment]
Do you add player classes or change the player spawn position some other way?

**Comment by LDami** [comment]
I've just put a "SetSpawnInfo" in the OnPlayerConnect event and called "Spawn" method later (after logged to database).

**Comment by LDami** [comment]
Seems to work if I add a class on GameMode init !

This was so simple but I've forgotten that you must have class. Sorry for that !
