### ISSUE TITLE
Server gets stuck for no apparent reason after 16-20 hours in development mode

### ISSUE THREAD

**Issue by SaSiNO97** [ikkentim/SampSharp#349]
After running for about 16/20 hours, my server suddenly gets stuck:
```
[15:10:20] [SampSharp:ERROR] Partial write -1/5.
[15:10:20] [SampSharp:ERROR] Failed to write to socket. Resource temporarily unavailable
[15:10:20] [SampSharp:ERROR] Unexpected disconnect of client. Failed to write to socket.
[15:10:21]   Filterscript 'intermission.amx' loaded.
```
![](https://i.ibb.co/pd6bfzt/image.png)

The server is not running in "production mode" (even though it's actually a production case, because I could not compile all my dependencies to x86).

I am using SampSharp 0.9.0 / 0.9.3

**Comment by ikkentim** [comment]
What server/OS/OS version are you using?

And out of interest, what dependencies could you not compile to x86?

**Comment by SaSiNO97** [comment]
I am using SA-MP Server 0.3.7-R2 on Ubuntu 18.04 LTS. 
I just noticed a fault of mine, on the server I am actually using SampSharp 0.8.0 and not 0.9.0 as I thought, but the game mode is compiled with 0.9.0, and this could be the cause of all my issues, including the callback param count error. I will fix the problem now and let you know.
About the dependencies, I am using various Nuget packages, including MySQL Connector, Dapper, MailKit, Newtonsoft JSON, and Mzsoft Bcrypt. I can't remember which packages prevented me to compile for Linux x86, I will tell you asap.

**Comment by SaSiNO97** [comment]
Ok now I have a clean 0.9.0 installation, with the 0.9.0 libSampSharp.so file, and 0.9.0 of SampSharp.GameMode, SampSharp.Core and SampSharp.Streamer, and the streamer.so plugin is version 2.9.4. Right now everything seems to be working fine, I will check whether after 2 days there were any issues.

**Comment by SaSiNO97** [comment]
Yeah, it crashed again and went into the intermission filterscript indefinitely (those who join would see "The server is restarting..")

**Comment by ikkentim** [comment]
Will be closing this due to #374 ... Keeping my fingers crossed open mp will provide a x64 server...
