### ISSUE TITLE
Problem with adding Cyrillic TextDraw

### ISSUE THREAD

**Issue by CharlieCheater** [ikkentim/SampSharp#351]
Greetings, **comrade**! I have a problem adding **Cyrillic** to **TextDraw**. Because of this, it seems, a small problem, my development stopped. :(
If i write "Test: Тестирование", Then as a result "Test: "

**Comment by ikkentim** [comment]
You have to select the encoding in your game mode startup using `UseEncoding` on your GameModeBuilder

**Comment by CharlieCheater** [comment]
I use Encoding. In particular, there are no problems with dialog boxes and chat...
Initially, Pawn also had problems with the Cyrillic alphabet, but a solution was proposed on the forums, which, unfortunately, does not work here.

**Comment by CharlieCheater** [comment]
A stop.  I'm stupid.  I changed the line, but did not save it ... The problem is solved.  :)
