### ISSUE TITLE
Error using SetMapIcon method

### ISSUE THREAD

**Issue by MrDave1999** [ikkentim/SampSharp#364]
When using the SetMapIcon method in any method defined in the Player class, the following error occurs:
`The name does not exist in the current context.`

What could be the problem?

**Comment by ikkentim** [comment]
The method does not exist in SampSharp.GameMode. I should add it.

**Comment by MrDave1999** [comment]
I had already put the namespace:
`using SampSharp.GameMode.World;`
In the same way it keeps giving the same error

**Comment by ikkentim** [comment]
That's because, like I tried to explain, I forgot to add the method to the BasePlayer class. I'll add it in the next update.
