### ISSUE TITLE
Print accents with SendClientMessage

### ISSUE THREAD

**Issue by MrDave1999** [ikkentim/SampSharp#366]
Does not print accents to the player (remains blank). What is the problem?
```c#
protected override void OnPlayerConnected(BasePlayer player, EventArgs e)
{
         base.OnPlayerConnected(player, e);
         player.SendClientMessage("íó");      
 }
```

**Comment by CiprianN23** [comment]
In order to use those types of characters you need to use a specific enconding. In this case i belive is cp1251

To do that you need to use `.UseEncoding()` in Programs.cs before `.Run()` in the gamemode builder

**Comment by MrDave1999** [comment]
I already had the `.UseEncoding()` (with `cp1251`) set, but even so, the accents still do not show.

**Comment by ikkentim** [comment]
Have you set your system locale to the corresponding value? This is the codepage the game uses: 
![image](https://user-images.githubusercontent.com/2820647/95297166-474a0e00-087a-11eb-85ea-5388f4dc0e9d.png)

**Comment by ikkentim** [comment]
Also, I think you need codepage cp1252 which should be OK for Spanish, I think cp1251 is for Cyrillic.

**Comment by MrDave1999** [comment]
I was using the wrong code page. It was the cp-1252. That solved the problem, thanks Tim.
