### ISSUE TITLE
Async event OnPlayerRequestSpawn in .Entities brake SetSpawnInfo

### ISSUE THREAD

**Issue by CiprianN23** [ikkentim/SampSharp#370]
So i was trying to make a custom class spawn which get spawn position from database using async and noticed that SetSpawnInfo is not called and im spawned in the default position 0 0 0

```
[Event]
        public async void OnPlayerRequestSpawn(Player player)
        {
            await Task.Delay(10);

            player.SetSpawnInfo(0, player.Skin, new Vector3(1, 1, 5) , 0.0f);
        }
```
This doesn't work im still spawned at default position. 
Instead this is working just fine:
```
[Event]
        public  void OnPlayerRequestSpawn(Player player)
        {
            player.SetSpawnInfo(0, player.Skin, new Vector3(1, 1, 5) , 0.0f);
        }
```
Also trying to get the task run synchronously its just block the entire execution of the event and im not spawned neither in default position

**Comment by ikkentim** [comment]
Default behaviour, see docs: "When you asynchronously await an operation, the execution of the callbacks will continue and the default return value will be returned from the callback because the main thread will not wait for asynchronous operations to complete.." https://sampsharp.net/threading

**Comment by CiprianN23** [comment]
In this case i will make it synchronously. I was expecting to work but well. Thanks for the answer
