### ISSUE TITLE
How can i upload to hosting?

### ISSUE THREAD

**Issue by hw2cb** [ikkentim/SampSharp#373]
Hello everyone, please help, how can I upload to hosting? What do I need to upload to hosting?I run samp-server and visual studio, how do I make the hosting run it itself?

Thanks for the help

**Comment by MrDave1999** [comment]
You must upload several things:

- The .dll where the gamemode code is stored (this is generated by VS).

- Dependencies (SampSharp.GameMode.dll and SampSharp.Core.dll)

- .NET Core Runtime

**Comment by Hy4e** [comment]
Hello. Full info about runnig in production you'll find in here: 
https://sampsharp.net/running-in-production

**Comment by hw2cb** [comment]
Hi, I was reading this. I have a two questions. Will my hosting for regular SAMP servers work? My hosting is on Debian, so I need to use Linux prerequisites?

**Comment by MrDave1999** [comment]
@hw2cb Yes, Debian is based on Linux. You need to upload the .NET Core Runtime package (x86) to the host, without that, it is impossible for the gamemode to load.

**Comment by hw2cb** [comment]
> @ hw2cb Да, Debian основан на Linux. Вам необходимо загрузить пакет .NET Core Runtime (x86) на хост, без этого загрузка игрового режима невозможна.

Thank you,  dotnet download from here https://sampsharp.net/running-in-production#prerequisites-linux-  for Linux? In my Program.cs file where is the entry point of the program, do I need to specify any additional methods for GameModeBuilder?
And SampSharp plugin in dll extension, do I need plugin with .so extension?

**Comment by Hy4e** [comment]
1. Open server.cfg.
2. Paste this:
```
coreclr dotnet/shared/Microsoft.NETCore.App/2.2.6
gamemode gamemode/MyGameMode.dll
```
But replace the paths with yours. Done.

**Comment by hw2cb** [comment]
> 1. Откройте server.cfg.
> 2. Вставьте это:
> 
> ```
> coreclr dotnet/shared/Microsoft.NETCore.App/2.2.6
> gamemode gamemode/MyGameMode.dll
> ```
> 
> Но замените пути на свои. Выполнено.

Yes. I understand. I just want to know which dotnet to download, the one listed on the site in the Linux prerequisites or is it newer?

**Comment by Hy4e** [comment]
Yes download from the site. If there are any problems we are in contact.

**Comment by hw2cb** [comment]
> Да скачай с сайта. Если возникнут проблемы, мы свяжемся с вами.

Thank you :+1:

**Comment by ikkentim** [comment]
Closing this question issue. You can reopen this issue, open a new one or join our discord if you have further questions.
