### ISSUE TITLE
Underground MP support

### ISSUE THREAD

**Issue by Nicoo34** [ikkentim/SampSharp#377]
Hey it's possible to add GTA underground MP support? It use the 0.3.7 but with a few new natives.

https://gtaundergroundmod.com/pages/ug-mp/documentation/native/gpci

**Comment by NeekoGta** [comment]
Just make a Wrapper like Streamer.

https://github.com/ikkentim/SampSharp-streamer

**Comment by ikkentim** [comment]
GPCI is a SA-MP native, available trough the BasePlayer class for .GameMode: https://github.com/ikkentim/SampSharp/blob/066511cc0224697e01f9f5bf61e4585a3c44ce87/src/SampSharp.GameMode/World/BasePlayer.cs#L591

**Comment by ikkentim** [comment]
I just noticed there are more available UG-MP methods. I think we're best off creating an extension library for this.
I'm currently busy with a bunch of other things, so I won't have this ready very quick.

If someone really needs it, they can create an extension for it, I'll gladly help them getting started in your discord group. If it can wait, I can make it myself later on when I've got the time.

**Comment by Berke-Alp** [comment]
> Hey it's possible to add GTA underground MP support? It use the 0.3.7 but with a few new natives.
> 
> https://gtaundergroundmod.com/pages/ug-mp/documentation/native/gpci

I made a wrapper for UG:MP you can download the source from [here](https://github.com/Berke-Alp/SampSharp.UndergroundMP). I added all the natives, you can create weapon, skin and vehicle types if you want.

**Comment by Nicoo34** [comment]
> > Hey it's possible to add GTA underground MP support? It use the 0.3.7 but with a few new natives.
> 
> > 
> 
> > https://gtaundergroundmod.com/pages/ug-mp/documentation/native/gpci
> 
> 
> 
> I made a wrapper for UG:MP you can download the source from [here](https://github.com/Berke-Alp/SampSharp.UndergroundMP). I added all the natives, you can create weapon, skin and vehicle types if you want.

Awesome thanks bro 👍

**Comment by ikkentim** [comment]
I see Berke made a library for this 👍 

https://github.com/Berke-Alp/SampSharp.UndergroundMP

I'm closing this issue
