### ISSUE TITLE
GlobalObject.Remove either RemoveBuildingForPlayer won't remove furniture objects!

### ISSUE THREAD

**Issue by spreadhaz** [ikkentim/SampSharp#394]
I'm trying to remove furniture objects for some default interiors in map.
It does delete them only while player is in their current position, but **they respawn** after player leaves the interior.
(It only works well for objects in exterior map)

**Comment by LDami** [comment]
Hey @spreadhaz, do you have the same behavior in Pawn ?

**Comment by ikkentim** [comment]
SampSharp simply calls the the natives. It looks like the problem you describe is unlikely to be caused by SampSharp.

Please reopen if you think I'm wrong here.
