### ISSUE TITLE
Invalid gamemode specified in server.cfg

### ISSUE THREAD

**Issue by EvilShadeZ** [ikkentim/SampSharp#410]
I have encountered a problem where the server won't launch and throw this error.
```
----------
Loaded log file: "server_log.txt".
----------

SA-MP Dedicated Server
----------------------
v0.3.7-R3, (C)2005-2019 SA-MP Team

[10:56:23] 
[10:56:23] Server Plugins
[10:56:23] --------------
[10:56:23]  Loading plugin: SampSharp
[10:56:23] [SampSharp:ERROR] Invalid gamemode specified in server.cfg.
[10:56:23]   Failed.
[10:56:23]  Loaded 0 plugins.

[10:56:23] 
[10:56:23] Filterscripts
[10:56:23] ---------------
[10:56:23]   Loaded 0 filterscripts.
```

Server.cfg
```
echo Executing Server Config...
lanmode 0
rcon_password randomtestpw
maxplayers 50
port 7777
hostname SA-MP 0.3 Server
gamemode0 empty 1
announce 0
chatlogging 0
weburl www.sa-mp.com
onfoot_rate 40
incar_rate 40
weapon_rate 40
stream_distance 300.0
stream_rate 1000
maxnpc 0
logtimeformat [%H:%M:%S]
language English
plugins SampSharp
```

The gamemode, filterscripts and plugins are in the appropriate folders. I've tried changing the net runtime from 6.0.4 to 6.0.3 and still no changes.

After some testing, it appears that I can get it to launch on the SampSharp v0.9.3, but not 0.10.0-alpha1 or newer.

**Comment by ikkentim** [comment]
Where is your gamemode located? SampSharp looks for a `.dll` file along with a `.runtimeconfig.json` file in the `<server-dir>/gamemode/` directory or one of its sub-directories. If SampSharp can't find a suitable gamemode, it will show this error.

**Comment by EvilShadeZ** [comment]
Ah, thanks! I must've somehow missed that a compiled mode needs to go in that folder, due to me just using the pipeline before. All working now.

**Comment by ikkentim** [comment]
Tip: If you want to debug your gamemode from visual studio, check this guide: https://sampsharp.net/getting-started
