### ISSUE TITLE
player.Vehicle returns EntityID instead of Vehicle

### ISSUE THREAD

**Issue by EvilShadeZ** [ikkentim/SampSharp#411]
Hi,

Using SampSharp 0.10.1 ECS, player.Vehicle returns SampSharp.Entities.EntityID instead of Vehicle. Is this the intended behaviour? If so how do I retrieve the Vehicle instance from EntityID?

Thanks.

**Comment by ikkentim** [comment]
You can get the Vehicle component through the EntityManager.

```cs
[PlayerCommand]
public void SampleCommand(Player player, IEntityManager entityManager)
{
    var vehicle = entityManager.GetComponent<Vehicle>(player.Vehicle);
}
```

I think I'll add some helper methods to make this easier in the future (e.g. `player.GetVehicle()`)

**Comment by y0ung3r** [comment]
#415

**Comment by ikkentim** [comment]
Closing since a PR has added this extension method.
