### ISSUE TITLE
config.json support on open.mp

### ISSUE THREAD

**Issue by EvilShadeZ** [ikkentim/SampSharp#420]
Hi, I have noticed that SampSharp is not letting us use the json configuration of open.mp, and refuses to run, even with the empty gamemode being run as a main script.

`[2022-09-22T15:50:08+0100] [Info] [SampSharp:ERROR] Can not load sampsharp if a non-SampSharp gamemode is set to load.
[2022-09-22T15:50:08+0100] [Info] [SampSharp:ERROR] Please ensure you set 'gamemode0 empty 1' in your server.cfg file.`

It would be appreciated if this could be fixed and I could start using the config.json rather than server.cfg

Many thanks.

**Comment by CiprianN23** [comment]
It was added in this commit https://github.com/ikkentim/SampSharp/commit/961d4f48afb77bb4cf37c18676083d0de334cea9

But is not in the released version. Only if you compile it yourself and test it.
