### ISSUE TITLE
Vistual Studio won't stop on breakpoint or not debugging when error occurrs 

### ISSUE THREAD

**Issue by spreadhaz** [ikkentim/SampSharp#421]
I can find the error if I do try catch thing, but it doesn't help at all
Am running on SampSharp 0.9.1

**Comment by ikkentim** [comment]
how are you running your server? if you follow these instructions debugging should work just fine

https://sampsharp.net/getting-started

**Comment by spreadhaz** [comment]
> how are you running your server? if you follow these instructions debugging should work just fine
> 
> https://sampsharp.net/getting-started

hello, It was working fine but I updated visual studio from 2019 to 2022 and things happened.
for now I'm just going to unistall and try again the instructions

**Comment by spreadhaz** [comment]
I created a new project and then dragged all things except project settings and now it works.
