### ISSUE TITLE
Failed to initialize CoreCLR runtime. Error -1

### ISSUE THREAD

**Issue by WeiduXx** [ikkentim/SampSharp#423]
Loading plugin: SampSharp
[SampSharp:INFO] Runtime path: E:\我的项目\SAMP\服务器\测试\runtime\shared\Microsoft.NETCore.App\6.0.3
[SampSharp:INFO] Game mode path: E:\我的项目\SAMP\服务器\测试\gamemodes\Debug\netcoreapp3.1\SampSharpGameMode1.dll
  Loaded.
 Loaded 1 plugins.

Started server on port: 7777, with maxplayers: 50 lanmode is OFF.

Filterscripts
---------------
  Loaded 0 filterscripts.

  Filterscript 'empty.amx' loaded.

SampSharp Plugin
----------------
v0.10.0, (C)2014-2022 Tim Potze

[SampSharp:INFO] Initializing .NET runtime...
[SampSharp:ERROR] CoreCLR.dll could not be found.
[SampSharp:ERROR] Failed to initialize CoreCLR runtime. Error -1.

**Comment by WeiduXx** [comment]
help

**Comment by ikkentim** [comment]
did you download the x86 version of the dotnet runtime?

**Comment by WeiduXx** [comment]
> 是否下载了 dotnet 运行时的 x86 版本？

yes

**Comment by WeiduXx** [comment]
![image](https://user-images.githubusercontent.com/26557202/205073635-4a07946d-7930-46bf-b907-53050a114634.png)
![image](https://user-images.githubusercontent.com/26557202/205073652-ffe66ea4-763f-4333-8f55-44e5e4dc0c6e.png)
![image](https://user-images.githubusercontent.com/26557202/205073679-4c04e187-e5ea-4a4d-833f-9afb385bd72c.png)

**Comment by WeiduXx** [comment]
![image](https://user-images.githubusercontent.com/26557202/205074713-ae15e54c-e65b-40d4-9c87-f4616d5e3db2.png)

**Comment by ikkentim** [comment]
there is a chance sampsharp doesn't support non-latin characters in the path to the server folder. could you try moving the server to the root of the E:\ drive and renaming the folder to, for example `server`?

That way we'll make sure the non-latin characters in the path are causing the problem.

**Comment by WeiduXx** [comment]
![image](https://user-images.githubusercontent.com/26557202/205075680-5c4cb533-3306-4d47-a8a9-b42d68c920b7.png)
Thank you for your help, this problem has been bothering me for a day.

**Comment by WeiduXx** [comment]
是否支持中文？

**Comment by WeiduXx** [comment]
Is Chinese supported?

**Comment by WeiduXx** [comment]
![image](https://user-images.githubusercontent.com/26557202/205078891-60b2780f-1b7b-4b7d-895f-b7f89a8261e8.png)

**Comment by WeiduXx** [comment]
![image](https://user-images.githubusercontent.com/26557202/205267505-707b9788-042f-471c-8a49-c16cfcbc015b.png)
![image](https://user-images.githubusercontent.com/26557202/205267555-b2d0932e-4f29-4072-939c-06feea08bdef.png)
![image](https://user-images.githubusercontent.com/26557202/205267639-ffff90e8-56b0-4ce4-8076-37ccc5fef79c.png)
Unable to get Chinese name
