### ISSUE TITLE
(question): coexistence compatibility between an existing gamemode and sampsharp

### ISSUE THREAD

**Issue by Duduzera1997** [ikkentim/SampSharp#432]
Hello!

After seeing this project, we were very interested to start using it, but we have some questions about the coexisting between a Gamemode created with pawn and SampSharp. 

Our Gamemode on pwn is based on modules, for example, we have one  `.inc` to display fps to player in game. 

Its possible to recriate this fps module on SampSharp and this execution work together another modules created on pawn?

Thanks for your disponibility, this project is amazing! 🙂

**Comment by CiprianN23** [comment]
As far i know , yes you can but at this moment only if you run the pawn code as filterscripts and have the gamemode be S# other than that yes they can coexist

**Comment by ikkentim** [comment]
you can run a pawn gamemode and a sampsharp gamemode at the same time.
