### ISSUE TITLE
Add GtaVehicle.GetComponentInSlot(CarModType);

### ISSUE THREAD

**Issue by ikkentim** [ikkentim/SampSharp#73]

**Comment by rrev** [comment]
Well, we could do the same thing as Bone #75 

    public virtual int GetComponentInSlot(int slot)
    {
        CheckDisposure();

        return Native.GetVehicleComponentInSlot(Id, slot);
    }

could be changed to

    public virtual int GetComponentInSlot(CarModType modType)
    {
        CheckDisposure();

        return Native.GetVehicleComponentInSlot(Id, (int) modType);
    }


instead of add an overload (as the title suggest) (the CarModType enum follows the same int of http://wiki.sa-mp.com/wiki/Componentslots)

**Comment by ikkentim** [comment]
Indeed
