### ISSUE TITLE
Create a way of updating gamemode files or restarting the gamemode without shutting down the server

### ISSUE THREAD

**Issue by ikkentim** [ikkentim/SampSharp#85]

**Comment by ikkentim** [comment]
Because you cannot reload the JIT runtime, I see no easy way of accomplishing this.

`
Note that for current versions of Mono, the mono runtime can’t be reloaded into the same process, so call mono_jit_cleanup() only if you’re never going to initialize it again.
`

The only way of reloading the gamemode at runtime would be to create a managed loading/unloading system for gamemodes.

**Comment by ikkentim** [comment]
Might be accomplish-able with appdomains.

**Comment by fvandillen** [comment]
That'd be lovely. You seem to be able to unload an appdomain, which creates a possibility to load/reload the script in a filterscript like fashion.

**Comment by ikkentim** [comment]
Yea. Hope to have some time for sampsharp soon :s

**Comment by fvandillen** [comment]
The same counts for my script based on Samp#. It's coming along nicely but just needs a load of time spent on it.
