### ISSUE TITLE
Question: Vehicle Callbacks

### ISSUE THREAD

**Issue by Just0wned** [ikkentim/SampSharp#93]
Hey there, i was wondering how i can detect when a hydra for example shoots a rocket or releases flares.

**Comment by rrev** [comment]
Is it possible in PAWN? (I'm not a SAMP/Pawn scripter anymore so I don't know/remember)

**Comment by Just0wned** [comment]
I never scripted in PAWN, so I have no idea, but I was wondering if would be possible in Samp# (the goal would be an ammo-system for the hydra, military helicopter and so on).

**Comment by ikkentim** [comment]
All you can do is detect key presses when a player is in a hydra, and assume it has shot a missile. There is however no flawless way to prevent missiles from firing

**Comment by Just0wned** [comment]
Thanks, well then i'll have to test a bit with that issue.
