### ISSUE TITLE
Enabletirepopping() is obsolete

### ISSUE THREAD

**Issue by fvandillen** [ikkentim/SampSharp#97]
Enabletirepopping has been removed since 0.3 (see: http://wiki.sa-mp.com/wiki/EnableTirePopping). Using it prints ```[23:36:59] EnableTirePopping() function is removed.```.

I suggest removing it from the API (or has this been left in for legacy purposes?).

**Comment by ikkentim** [comment]
AllowAdminTeleport() is obsolete as well. I've kept them in because SA-MP have kept them in as well, but I think I might remove them since they're pointless anyways.

**Comment by rrev** [comment]
Soo, we'll keep them? SampSharp always works with the latest SA-MP version so it's pointless to have them since they will never be used

**Comment by ikkentim** [comment]
They are rather pointless really.. I think I'll look which natives are obsolete and remove those in the next release.
