### ISSUE TITLE
Update Get/SetVehicleParamsEx parameters

### ISSUE THREAD

**Issue by ikkentim** [ikkentim/SampSharp#99]
Based on Zeex/sampgdk@09d4b1066bca714100ad1577b99a6bfbb23aec29

**Comment by rrev** [comment]
How do you generate sampgdk c/h files? I tried to compile sampgdk but I cannot find them (tried with COMPILE_STATIC).

**Comment by ikkentim** [comment]
https://github.com/Zeex/sampgdk#build-instructions

**Comment by ikkentim** [comment]
So the cmake command should look like:
`cmake .. -DSAMPGDK_BUILD_AMALGAMATION =ON`
